### ISSUE TITLE
How do I import logs from kubernete master servers to splunk ?

### ISSUE THREAD

**Issue by rufengxu** [splunk/splunk-connect-for-kubernetes#106]
How do I import logs from kubernete master servers to splunk ?  Do I need to leverage this splunk-connect-for-kubernetes or I should use regular data forwarder ?

Thanks,
Rufeng

**Comment by VinceMD** [comment]
For me (kube-aws), I had to add 
```
tolerations:
  - key: node.alpha.kubernetes.io/role
    operator: "Exists"
    effect: "NoSchedule" 
``` 
in values.yaml. It started a few more agent for each of my master and then all the kube-system logs started to come to Splunk
