### ISSUE TITLE
Performance issues with Metrics and Metrics Aggregator - OOM and slow ingest

### ISSUE THREAD

**Issue by dtregonning** [splunk/splunk-connect-for-kubernetes#107]
**Issue:**
We've identified an issue with the Metrics and Metrics Aggregator fluentd plugins not buffering chunks correctly with the settings provided inside helm charts.
https://github.com/splunk/splunk-connect-for-kubernetes/blob/master/helm-chart/splunk-kubernetes-metrics/values.yaml#L103
This is causing the plugins to get overwhelmed.

**Cause**
Further testing has determined that the value provided as the default configuration for 
`chunk_limit_records: 1000000
`
is incorrect. This is causing Metric and Metrics Aggregator events to not buffer at the expected interval. 

**Fix**

Inside the values.yaml used to deploy Splunk Connect for Kubernetes please include the buffer and aggregator buffer lines with the updated chunk_limit_records value. This is only applicable for Splunk Connect for Kubernetes 1.1.0

```
splunk-kubernetes-metrics:
  kubernetes:
    ...
  splunk:
    ...
  image:
    ...
  buffer:
    chunk_limit_records: 10000
  aggregatorBuffer:
    chunk_limit_records: 10000
```
