### ISSUE TITLE
Add securityContext and env var SSL_CERT_FILE to DaemonSets and Deployments

### ISSUE THREAD

**Issue by ron1** [splunk/splunk-connect-for-kubernetes#130]
In order to support secure Kubernetes installations, including OKD/OCP, modify the logging DaemonSet, metrics DaemonSet, and metrics aggregator Deployment as follows:

Use below as replacement for line spec.template.spec.containers.env:
```
securityContext:
  privileged: true
  runAsUser: 0
env:
  - name: SSL_CERT_FILE
    value: /fluentd/etc/splunk/hec_ca_file
```

Also modify the objects Deployment as follows:

Use below as replacement for line spec.template.spec.containers.env:
```
env:
  - name: SSL_CERT_FILE
    value: /fluentd/etc/splunk/hec_ca_file
```
