### ISSUE TITLE
"Failed to scrape metrics" in v1.1, worked  in v1.0.1

### ISSUE THREAD

**Issue by bdschaap** [splunk/splunk-connect-for-kubernetes#157]
**What happened**:
I am not receiving K8s metrics in Splunk.  I configured Splunk Connect for Kubernetes v1.1 in a one node cluster within Docker Desktop for Windows.  I am receiving the following error messages -
"[error]: #0 Failed to scrape metrics, error=, #<NoMethodError: undefined method `[]' for nil:NilClass>"
"[error]: #0 suppressed same stacktrace"
These errors appear in the kube:container:splunk-fluentd-k8s-metrics-agg sourcetype.

**What you expected to happen**:
I'm expecting K8s metrics to be sent to Splunk.  It works in v1.0.1 but no longer works in v1.1.

**How to reproduce it (as minimally and precisely as possible)**:
1) Configure Docker Desktop for Windows and enable Kubernetes
2) Install Splunk Connect for Kubernetes v1.1
3) Go to Splunk and you'll see that metrics are not available and the error messages above will be in the logs.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Ruby version (use `ruby --version`):
Not sure

- OS (e.g: `cat /etc/os-release`):
Windows Server 2019
- Splunk version:
7.2.6
- Others:
Splunk Connect for Kubernetes 1.1

**Comment by matthewmodestino** [comment]
Hi @bdschaap!

Can you share your values.yaml and grab the rendered runtime config from `kubectl logs -f` ? We dump the config when the pods spin up, handy for troubleshooting. 

Here is what I run in my docker for mac deploy:

```
#local config for metrics chart
splunk-kubernetes-metrics:
  kubernetes:
    clusterName: docker-for-mac
    kubeletPort: 10250
    useRestClientSSL: true
    insecureSSL: true
  buffer:
    chunk_limit_records: 10000
  aggregatorBuffer:
    chunk_limit_records: 10000
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-metrics
  splunk:
    hec:
      indexName: cm_metrics
```


Note the buffer configs to workaround this bug:
https://github.com/splunk/splunk-connect-for-kubernetes/issues/107
