### ISSUE TITLE
splunk-kubernetes-objects configmap.yaml format error

### ISSUE THREAD

**Issue by Gimi** [splunk/splunk-connect-for-kubernetes#18]
Behavior:
* Define multiple configs for an object, e.g.
```yaml
objects:
  core:
    v1:
      - name: pods
        namespace: default
        mode: pull
        interval: 60m
```

Expected
* Objects are pulled/watched with the defined properties

Actual
* Get config error
