### ISSUE TITLE
clusterName not honoring global override

### ISSUE THREAD

**Issue by gmichels** [splunk/splunk-connect-for-kubernetes#184]
**What happened**:
Deployed the `splunk-connect-for-kubernetes` 1.2.0 chart configured with a custom `global.kubernetes.clusterName` and events showed up with the default `cluster_name` value

**What you expected to happen**:
Events should use my overridden `clusterName`

**How to reproduce it (as minimally and precisely as possible)**:
```
global:
  splunk:
    hec:
      protocol: https
      host: foo.bar
      token: very_secret

  kubernetes:
    clusterName: my_custom_name
```

**Anything else we need to know?**:
Fix is to set `kubernetes.clusterName` to `null` in each dependency chart as then the template logic will correctly apply, e.g.:

```
    <filter kube.**>
      @type jq_transformer
      jq '.record.cluster_name = "{{ or .Values.kubernetes.clusterName .Values.global.kubernetes.clusterName }}" | .record'
    </filter>
```
