### ISSUE TITLE
Metrics are not going to specified metrics index

### ISSUE THREAD

**Issue by MarkPare** [splunk/splunk-connect-for-kubernetes#209]
**What happened**:
metrics are not going to metrics index (`my-metrics-index`) in splunk. 

**What you expected to happen**:
metrics logging goes to metrics index.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Confirmed that my metrics index `my-metrics-index` is of type `metric`.

**Environment**:
- Kubernetes version (use `kubectl version`):
1.11.0
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version:
7.0
- Others:

`values.yaml` contents:
```
global:
  logLevel: info
  splunk:
    hec:
      token: my-token
      host: my-host.com
      port: 8088
      protocol: http
  kubernetes:
    clusterName: "my-cluster"

splunk-kubernetes-logging:
  splunk:
    hec:
      indexName: my-logging-index

splunk-kubernetes-objects:
  splunk:
    hec:
      indexName: my-objects-index

splunk-kubernetes-metrics:
  splunk:
    hec:
      indexName: my-metrics-index
```
