### ISSUE TITLE
splunk-kubernetes-logging - allow pod and container exclusion

### ISSUE THREAD

**Issue by stiller-leser** [splunk/splunk-connect-for-kubernetes#228]
Hi everybody,

first off: Great work. This is really easy to use!

**What would you like to be added**:

I'd like to be able to limit the collected pod logs, in order to limit what is send to Splunk. Currently I am doing the following:

```yaml
global:
  fluentd:
    # path of logfiles, default /var/log/containers/*.log
    path: /var/log/containers/*.log
    # paths of logfiles to exclude. object type is array as per fluentd specification:
    # https://docs.fluentd.org/input/tail#exclude_path
    exclude_path:
     - /var/log/containers/prometheus*.log
     - /var/log/containers/istio*.log
     - /var/log/containers/kube*.log
```
This works if I want to exclude pods (even though it is cumbersome), but this won't affect side car containers. So for Istio for example, I might only be interested in the logs of my apps, but not of the istio-proxy sidecar.

**Why is this needed**:

Limit the input into Splunk and increase visibility
