### ISSUE TITLE
Multiline events not flushing until next event occurs

### ISSUE THREAD

**Issue by nokesc** [splunk/splunk-connect-for-kubernetes#243]
I have the following configuration:
```
  logs:
    my-app:
       from:
         pod: my-app
         container: my-app
       multiline:
         firstline: /^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d,\d{3}[+-]\d\d \[[a-zA-Z]+\] \[/
       sourcetype: app:log4j2
```
I am getting events with multi-lines as I expect.  The problem is that the event is buffered and isn't delivered until another event has started.  The timestamp in splunk is the timestamp of when the next events starts buffering.  For example, if event-a is delivered, then it buffers somewhere in fluentd.  Let's say 30 seconds pass, and then event-b comes into the log, at that point event-a is sent to Splunk with a timestamp with +30 seconds.

At first I thought perhaps something was wrong with the flush_interval for the concat plugin:
In **splunk-kubernetes-logging/templates/configMap.yaml**, line 160:
**flush_interval {{ $logDef.multiline.flushInterval | default "5s" }}**
I thought this value is supposed to be **5** instead of **5s**.  See [fluentd concat](https://github.com/fluent-plugins-nursery/fluent-plugin-concat) documentation.  However, that update made no difference.  Also, I can see that this flush does work.  From the fluentd log:
```
2019-09-20 18:21:22 +0000 [info]: #0 Timeout flush: tail.containers.var.log.containers.my-app-655555b857-jlknz_default_my-app-80fb6e9b4517fbb754758b2e821464384bd30a5e2ce4f538cd050ef4c3e1c281.log:stdout
```
So I can see fluentd saying the concat flush occurred, but the event does not get sent.
