### ISSUE TITLE
Global values.yaml no longer working

### ISSUE THREAD

**Issue by sidssn** [splunk/splunk-connect-for-kubernetes#259]
**What happened**: We are providing global values from the parent chart to the configMap but they are not getting picked up, instead are getting overridden by the local values.yaml values

**What you expected to happen**: We would expect the global variables set in the values.yaml of the parent chart to be picked and assigned

**How to reproduce it (as minimally and precisely as possible)**: Deploying any one of the helm chart

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  1.13
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):  Mac OS
- Splunk version: 1.2.0
- Others:

**Comment by chaitanyaphalak** [comment]
can be specific about which values?

**Comment by paulalex** [comment]
I think the variables that are not being picked up described in the values.yaml in the below blog post. 

Only the global section is being picked up and not the `splunk-kubernetes-objects` or `splunk-kubernetes-metrics` so the index isnt being applied. 
 
https://www.splunk.com/blog/2019/03/01/deploy-splunk-enterprise-on-kubernetes-splunk-connect-for-kubernetes-and-splunk-insights-for-containers-beta-part-3.html

**Comment by chaitanyaphalak** [comment]
The implementation is same for all the charts, 
https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-kubernetes-logging/templates/configMap.yaml#L246
https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-kubernetes-metrics/templates/configMap.yaml#L104
https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-kubernetes-metrics/templates/configMap.yaml#L104

It looks like it might be a misconfiguration, could you post the redacted configmap?

Thanks

**Comment by paulalex** [comment]
I havent amended the config map but if I do then it works, all I am doing is using the template as in the blog post but the config map when viewed in k8s doesnt have any of the values in it, below is the `values.yaml`:

```
global:
  logLevel: info
  kubernetes:
    clusterName: dev-cluster  
  splunk:
    hec:
      protocol: https
      indexRouting: true
      indexRoutingDefaultIndex: main
      loggingEnvironment: dev
      nonprodLoggingEnvironment: nonprod
      prodLoggingEnvironment: prod
      prodNamespaceIdenfifier: -prod
      insecureSSL: true
      port: 8088

# Local config for logging chart
splunk-kubernetes-logging:
  journalLogPath: /run/log/journal
  splunk:

# Local config for objects chart
splunk-kubernetes-objects:
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-objects
  kubernetes:
    insecureSSL: true
  objects:
    core:
      v1:
        - name: pods
        - name: namespaces
        - name: nodes
        - name: services
        - name: config_maps
        - name: secrets
        - name: persistent_volumes
        - name: service_accounts
        - name: persistent_volume_claims
        - name: resource_quotas
        - name: component_statuses
        - name: events
  #        mode: watch
    apps:
      v1:
        - name: deployments
        - name: daemon_sets
        - name: replica_sets
        - name: stateful_sets
  splunk:
    hec:
      indexName: eks_meta_k8s_dev

# Local config for metrics chart
splunk-kubernetes-metrics:
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-metrics
  splunk:
    hec:
      indexName: eks_metrics_k8s_dev
```

Values in the global section are applied, but none of the values from either of the sections for objects or metrics are, and I also dont think properties from the logging section are being applied either, so only the global section at the top (.Values.global.splunk.hec.indexName) works.

If however I make a change like the following it does work:

```
{{- with or .Values.**my_values_section**.splunk.hec.indexName .Values.global.splunk.hec.indexName }}
        index {{ . }}
{{- end }}
```

```
**my_values_section**:
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-metrics
  splunk:
    hec:
      indexName: eks_metrics_k8s_dev
```
