### ISSUE TITLE
Make dependency charts optional

### ISSUE THREAD

**Issue by wendorf** [splunk/splunk-connect-for-kubernetes#26]
For customers who don't want to use certain components like metrics, it would be nice to be able to fully disable the chart with a parameter. See https://github.com/helm/charts/blob/0ef9bada8a340798fb5f6e334e97689049fb48c3/stable/concourse/requirements.yaml#L5 for an example:

```
dependencies:
- name: postgresql
  version: 0.13.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
```
