### ISSUE TITLE
proper configuration for use with splunk light cloud

### ISSUE THREAD

**Issue by mateodelnorte** [splunk/splunk-connect-for-kubernetes#285]
I'm trying to stream data to my instance of splunk light with the following configuration: 
```
logging:
  splunk-kubernetes-logging:
    secret:
      create: true
    splunk:
      hec:
        host: beep-boop
        insecureSSL: false
        port: 443
        token: vault:darkstore-dev/logging/splunk/hec:token
```
I get the following error with this configuation: 
```
2019-11-13 19:35:38 +0000 [error]: #0 Failed POST to https://beep-boop.cloud.splunk.com/services/collector, response: <!doctype html><html><head><meta http-equiv="content-type" content="text/html; charset=UTF-8"><meta http-equiv="refresh" content="1;url=https://beep-boop.cloud.splunk.com/en-US/services/collector"><title>303 See Other</title></head><body><h1>See Other</h1><p>The resource has moved temporarily <a href="https://beep-boop.cloud.splunk.com/en-US/services/collector">here</a>.</p></body></html>
```
I've tried various configurations, to no avail. I've tried not have `insecureSSL: false`, I've tried `port: 8089` as well as `port: 9997`, which is configured for data receive in my Splunk Light cloud UI. 

Any tips on getting this to work?

**Comment by mateodelnorte** [comment]
updates with additional configuration attempts: 

the following
```
logging:
  splunk-kubernetes-logging:
    secret:
      create: true
    splunk:
      hec:
        host: beep-boop
        port: 8089
        token: vault:darkstore-dev/logging/splunk/hec:token
```
yields
```
  2019-11-13 20:11:10 +0000 [warn]: #0 suppressed same stacktrace
2019-11-13 20:11:12 +0000 [warn]: #0 failed to flush the buffer. retry_time=2 next_retry_seconds=2019-11-13 20:11:14 +0000 chunk="5973ff6e7d7fda638a18da30116f262f" error_class=OpenSSL::SSL::SSLError error="SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)"
```

**Comment by mateodelnorte** [comment]
the following:

```
logging:
  splunk-kubernetes-logging:
    secret:
      create: true
    splunk:
      hec:
        host: beep-boop
        insecureSSL: true
        port: 8089
        token: vault:darkstore-dev/logging/splunk/hec:token
```
yields
```
2019-11-13 20:27:22 +0000 [error]: #0 Failed POST to https://beep-boop:8089/services/collector, response: <?xml version="1.0" encoding="UTF-8"?>
<response>
  <messages>
    <msg type="WARN">call not properly authenticated</msg>
  </messages>
</response>
```

**Comment by matthewmodestino** [comment]
I don't believe the URL being used is correct. Splunk Cloud has a specific scheme for urls. Can you check you Splunk Cloud LIght UI under data inputs to see if it guide you for the proper URL or consult the splunk cloud getting data in docs. I am checking them now...

**Comment by mateodelnorte** [comment]
I'm using `beep-boop` in place of the actual host, which is of the form `prd-p-7abc123aab56.cloud.splunk.com

**Comment by mateodelnorte** [comment]
Note, I get the same error using curl from the container: 
```
 curl -k https://prd-p-[my instance id].cloud.splunk.com:8089/services/collector/event -H "Authorization: Splunk $SPLUNK_TOKEN_HEC" -d '{ "event": "hello world1"}'
<?xml version="1.0" encoding="UTF-8"?>
<response>
  <messages>
    <msg type="WARN">call not properly authenticated</msg>
  </messages>
</response>
```

**Comment by mateodelnorte** [comment]
I can confirm the instance id and token env var are correct.

**Comment by matthewmodestino** [comment]
8089 is definitely incorrect for HEC. 8089 is splunkd port.

**Comment by mateodelnorte** [comment]
That's not what I saw in the documentation: https://docs.splunk.com/Documentation/SplunkLight/6.6.3/GettingStarted/UsingHTTPeventcollector

![image](https://user-images.githubusercontent.com/554847/68806836-4b4ebb00-062c-11ea-8f35-b071e3b2a18c.png)

FWIW: 
```
curl -k https://prd-p-[my instance id].cloud.splunk.com:443/services/collector/event -H "Authorization: Splunk $SPLUNK_HEC_TOKEN" -d '{ "event": "hellow worldz"}'
<!doctype html><html><head><meta http-equiv="content-type" content="text/html; charset=UTF-8"><meta http-equiv="refresh" content="1;url=https://prd-p-8mhj559nnv26.cloud.splunk.com/en-US/services/collector/event"><title>303 See Other</title></head><body><h1>See Other</h1><p>The resource has moved temporarily <a href="https://prd-p-8mhj559nnv26.cloud.splunk.com/en-US/services/collector/event">here</a>.</p></body></html>
```

**Comment by mateodelnorte** [comment]
Looks like I need to use a downloadable credentials file, here: https://docs.splunk.com/Documentation/SplunkLight/6.6.3/Cloud/GettingdataintoSplunkLightcloudserviceusingLinux#Step_4:_Install_the_universal_forwarder_credentials

**Comment by mateodelnorte** [comment]
Scratch that, looks like you can use the HEC, as described in the previous link. Just not clear why I'm not authenticating correctly. https://docs.splunk.com/Documentation/SplunkLight/6.6.3/GettingStarted/UsingHTTPeventcollector

**Comment by matthewmodestino** [comment]
Any updates @mateodelnorte ?

**Comment by mateodelnorte** [comment]
Yep. Our configuration ended up looking like: 
```
logging:
  splunk-kubernetes-logging:
    secret:
      create: true
    splunk:
      hec:
        host: input-prd-p-[splunk instance id].cloud.splunk.com
        insecureSSL: true
        port: 8088
        token: vault:dev/logging/splunk/hec:token
```
