### ISSUE TITLE
Question: Capture specific logs for a given container?

### ISSUE THREAD

**Issue by ajsaclayan** [splunk/splunk-connect-for-kubernetes#298]
Hi all,

Following this example:
https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-kubernetes-logging/examples/use_logs.yaml

I have some logs (log1 and log2) that live in acontainer at path /opt/containername/.  I've SSH'd into the container and verified the path to these logs.

I want to tail these logs.  In my values.yaml I've defined this snippet:
```
logs:
  container-name:
    from:
      file:
        path: /opt/containerName/log1.log
```

Retrieving the logs of the splunk-connect pod that lives on the same node as the container:
`2019-12-17 21:35:16 +0000 [warn]: #0 /opt/containername/log1.log not found. Continuing without tailing it.`

Any guidance would be appreciated.

Thanks!
AJ
