### ISSUE TITLE
Unknown filter plugin 'kubernetes_metadata'

### ISSUE THREAD

**Issue by haisum** [splunk/splunk-connect-for-kubernetes#301]
**What happened**:

pods crashed with error:
```
2020-01-06 17:15:02 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2020-01-06 17:15:02 +0000 [error]: config error file="/fluentd/etc/fluent.conf" 
error_class=Fluent::ConfigError error="Unknown filter plugin 'kubernetes_metadata'. 
Run 'gem search -rd fluent-plugin' to find plugins"
```
**What you expected to happen**:

pods to start without error

**How to reproduce it (as minimally and precisely as possible)**:

- clone latest develop branch
- make
- helm install splunk-connect -n splunk -f ~/values.yaml build/splunk-kubernetes-logging-1.3.0.tgz
- pods start crashing

**Anything else we need to know?**:

I am building unreleased chart because I need k8sMetadata configuration.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version:
- Others:

**Comment by rockb1017** [comment]
Hello, Could you give me the image name that your implementation is using ?

**Comment by haisum** [comment]
What do you mean by image name? I used the default values mostly.

Here's my values.yaml:

```yaml
# Splunk Connect for Kubernetes is a umbraller chart which itself does not contain any template,
# so there is no configurable parameters for itself.

# Use global configurations for shared configurations between sub-charts.
# Supported global configurations:
#
global:
#   logLevel:
   splunk:
     # HEC related configurations
     hec:
       protocol: http
       host: <host>
       port: 8088
       token: <token>
       indexName: kubernetes_cluster_logs
       # connection to splunk is insecure
       insecureSSL: true
   kubernetes:
     clusterName: "kubernetes"
   fluentd:
     exclude_path:
       - /var/log/containers/kube*.log
       - /var/log/containers/splunk*.log
       - /var/log/containers/etcd*.log

# For other configurations for sub-charts, please check their values.yaml for details.
## Enabling logging will install the `splunk-kubernetes-logging` chart to a kubernetes
## cluster to collect logs generated in the cluster to a Splunk indexer/indexer cluster.
logging:
  enabled: true

## Enabling objects will install the `splunk-kubernetes-objects` chart to a kubernetes
## cluster to collect kubernetes objects in the cluster to a Splunk indexer/indexer cluster.
objects:
  enabled: false

## Enabling metrics will install the `splunk-kubernetes-metrics` chart to a kubernetes
## cluster to collect metrics of the cluster to a Splunk indexer/indexer cluster.
metrics:
  enabled: false

splunk-kubernetes-logging:
  logs:
   busybox:
    from:
     pod: busybox
    multiline:
      firstline: /^\d{4}-\d{2}-\d{2}/
      flushInterval: 2s
  indexFields: []
  k8sMetadata:
   # Pod labels to collect
   podLabels:
    - app
    - version
```
