### ISSUE TITLE
Missing namespace, pod and container_id when using CRI format 

### ISSUE THREAD

**Issue by matthewmodestino** [splunk/splunk-connect-for-kubernetes#305]
**What happened**:

Tried to deploy SCK 1.3.0 on MicroK8s which uses containerd (similar to Openshift 4.x) and have observed that when I set the format to `cri` that the chart doesn't render indexed fields for `namespace`, `pod` and `container_id` on the fluentd `outputs.conf`, specifically in `fields`. 

**What you expected to happen**:

I expected the logging pod would send the same fields we sent when using docker. I expected there would be some variance at the container level but not at the k8s level. 

**How to reproduce it (as minimally and precisely as possible)**:

Spin Ubuntu VM 

Install microk8s (its super easy), be sure to enable the dns, rbac and storage plugins. 

Deploy SCK

Note the output.conf that is rendered, and how it is missing the `fields` config for the missing fields. 

**Anything else we need to know?**:

Here is my values.yaml, including workaround by declaring the fields I wanted from the payload with the new `indexedFields` option 

```
#global settings
global:
  logLevel: info
  splunk:
    hec:
      protocol: http
      insecureSSL: true
      host: splunk-mattymo
      token: 00000000-0000-0000-0000-000000000000
      port: 8088

#local config for logging chart
splunk-kubernetes-logging:
  containers:
    pathDest: /var/snap/microk8s/common/var/lib/docker/
    logFormatType: cri
    logFormat: "%Y-%m-%dT%H:%M:%S.%N%:z"
  kubernetes:
    clusterName: MicroK8s
  journalLogPath: /var/log/journal
  splunk:
    hec:
      indexName: em_events
  indexFields: ["pod", "namespace","container_id"]

#local config for objects chart
splunk-kubernetes-objects:
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-objects
  kubernetes:
    insecureSSL: true
    clusterName: MicroK8s
  splunk:
    hec:
      indexName: em_meta

#local config for metrics chart
splunk-kubernetes-metrics:
  metricsInterval: 60s
  kubernetes:
    insecureSSL: true
    clusterName: MicroK8s
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-metrics
  splunk:
    hec:
      indexName: em_metrics
```

**Environment**:
- Kubernetes version (use `kubectl version`):

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

```

- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version: 8.0.1
- Others:
Microk8s/containerd.
