### ISSUE TITLE
Expose concat controls in logging Helm Chart

### ISSUE THREAD

**Issue by matthewmodestino** [splunk/splunk-connect-for-kubernetes#315]
<

**What would you like to be added**:

I would like to be able to have access to more `concat` settings when defining log sources in the helm chart, especially `separator`, regex settings, and partial settings for when docker might truncate ahead of us. (the truncate at 16K and set a partial flag that concat appears to support)

https://github.com/fluent-plugins-nursery/fluent-plugin-concat#configuration

```
  logs:
    nginx-ingress:
      from:
        pod: nginx-ingress
        container: nginx-ingress-controller
      #keep default sourcetype for sake of avoiding complexity
      #if you really want to customize sourcetype you can 
      #sourcetype: nginx:ingress:controller
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d\s\d{2}:\d{2}:\d{2}.\d{6}\s|^\d+\.\d+\.\d+\.\d+[^\[]+|\d{4}\/\d{2}\/\d{2}\s\d{2}:\d{2}:\d{2}[^\[]+|^NGINX\sIngress\scontroller|^----------/
    ghost:
      from:
        pod: ghost
        container: ghost
      multiline:
        firstline: /^\[\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\]/
```

**Why is this needed**:

Different log streams need different settings based on the log formats, for example, these nginx & ghost blog multiline log needed newline separators, where as a stacktrace may not. Currently I have to edit the configmap in cluster or burn into the templates to acomplish this. 

Ideally id like to see these options exposed in annotations. 

![image](https://user-images.githubusercontent.com/31549209/73593478-ed1ad100-44d2-11ea-9bfd-98d120f3359a.png)

![image](https://user-images.githubusercontent.com/31549209/73593486-015ece00-44d3-11ea-956f-0d0f79e5c0d1.png)
