### ISSUE TITLE
Log format type "cri" not working as expected

### ISSUE THREAD

**Issue by mcpdev80** [splunk/splunk-connect-for-kubernetes#357]
The Release Notes for 1.3.0 document that CRI-O is also supported here (https://github.com/splunk/splunk-connect-for-kubernetes/releases). We tried that right away, and also rebuilt the Helm Charts with the corresponding variant: 

Values.yml:
                
                  # Log format type, "json" or "cri"
                  logFormatType: cri
                

Unfortunately this did not change the final result. It always said "json" in the template.

ConfigMap: 
                
                 # CRI Log Example (not supported):
                      <parse>
                        @type json
                

If I chang the parameter there manually, the Splunk-Connector Pods will not start: 

ConfigMap: 

                # CRI Log Example (not supported):
                      <parse>
                        @type cri
              

Pod Logs: 

                error="Unknown parser plugin 'cri'.

I am also slightly irritated by the message, CRI not supported? In the release notes it was announced as news.

The only way to get the splunk-connector working with CRI-O Logs is a workaround using regex.

ConfigMap:
               
      <parse>
        @type regexp
        expression /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/

**Environment**:
- OpenShift version: 4.3.*
- Splunk-connector version: 1.4

**Comment by matthewmodestino** [comment]
I was able to deploy 1.3 like this, with the only bug being 1.3 is missing indextime field definitions in the chart. Please share the steps you are taking cause I was able to render the chart. 

```
global:
  logLevel: info
  splunk:
    hec:
      protocol: https
      insecureSSL: true 
      host: splunk-mattymo
      token: 00000000-0000-0000-0000-000000000000
      port: 8088

#local config for logging chart
splunk-kubernetes-logging:
  containers:
    #for use with docker in past versions of MicroK8s       
    #pathDest: /var/snap/microk8s/common/var/lib/docker/
    logFormatType: cri
    logFormat: "%Y-%m-%dT%H:%M:%S.%N%:z"
  kubernetes:
    clusterName: MicroK8s
  journalLogPath: /var/log/journal
  splunk:
    hec:
      indexName: em_events
  # sck-1.3.0 cri-o workaround, fixed in next release. 
  indexFields: ["pod", "namespace","container_id"]
  logs:
    nginx-ingress:
      from:
        pod: nginx-ingress
        container: nginx-ingress-controller
      #keep default sourcetype for sake of avoiding complexity
      #if you really want to customize sourcetype you can 
      #sourcetype: nginx:ingress:controller
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d\s\d{2}:\d{2}:\d{2}.\d{6}\s|^\d+\.\d+\.\d+\.\d+[^\[]+|\d{4}\/\d{2}\/\d{2}\s\d{2}:\d{2}:\d{2}[^\[]+|^NGINX\sIngress\scontroller|^----------/

#local config for objects chart
splunk-kubernetes-objects:
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-objects
  kubernetes:
    insecureSSL: true
    clusterName: MicroK8s
  objects:
    core:
      v1: [{"name":"pods", "interval":"60s"},{"name":"nodes", "interval":"60s"},{"name":"component_statuses", "interval":"60s"},{"name":"config_maps", "interval":"60s"},{"name":"namespaces", "interval":"60s"},{"name":"persistent_volumes", "interval":"60s"},{"name":"persistent_volume_claims", "interval":"60s"},{"name":"resource_quotas", "interval":"60s"},{"name":"services", "interval":"60s"},{"name":"service_accounts", "interval":"60s"},{"name":"events", "mode":"watch"},]
    apps:
      v1:
        [{"name":"daemon_sets", "interval":"60s"},{"name":"deployments", "interval":"60s"},{"name":"replica_sets", "interval":"60s"},{"name":"stateful_sets", "interval":"60s"},]
  splunk:
    hec:
      indexName: em_meta

#local config for metrics chart
splunk-kubernetes-metrics:
  metricsInterval: 60s
  kubernetes:
    #opened issue to allow user to set port for metrics and metrics-agg separately, as seems to be required in MicroK8s
    kubeletPort: 10255
    useRestClientSSL: false
    insecureSSL: true
    clusterName: MicroK8s
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-metrics
  splunk:
    hec:
      indexName: em_metrics
```
