### ISSUE TITLE
definition/values for APPS_OBJ?

### ISSUE THREAD

**Issue by gliptak** [splunk/splunk-connect-for-kubernetes#368]
https://company.splunkcloud.com/en-US/app/splunk_app_infrastructure/configure shows following configuration code:

```
export MONITORING_MACHINE= && export HEC_TOKEN= && export HEC_PORT= && export GLOBAL_HEC_INSECURE_SSL=false && export OBJECTS_INSECURE_SSL=true && export METRICS_INSECURE_SSL=true && export JOURNALD_PATH=/run/log/journal && export KUBELET_PROTOCOL=https && export METRICS_INDEX=em_metrics && export LOG_INDEX=main && export META_INDEX=em_meta && export CLUSTER_NAME= && export HELM_RELEASE_NAME= && export KUBERNETES_NAMESPACE= && export CORE_OBJ=pods,nodes && export APPS_OBJ= && files=("kubernetes_connect_template.yaml" "deploy_sck_k8s.sh") && for each in "${files[@]}"; do wget -O-  https://company.splunkcloud.com/en-US/static/app/splunk_app_infrastructure/kubernetes_connect/"$each" > $each; done && wget https://github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.2.0/splunk-connect-for-kubernetes-1.2.0.tgz -O splunk-connect-for-kubernetes.tgz && bash deploy_sck_k8s.sh
```

after filling out fields ```APPS_OBJ``` doesn't get a value

Could you point me to some details on ```APPS_OBJ```?

https://github.com/splunk/splunk-connect-for-kubernetes/issues/35
https://github.com/splunk/splunk-connect-for-kubernetes/issues/265

**Comment by chaitanyaphalak** [comment]
@matthewmodestino is more familiar with SAI

**Comment by matthewmodestino** [comment]
The Objects map to  splunk object pod configmap, setting the the objects to collect. Splunk app for infra has a directory called `~/appserver/static/` where all the add data templates are kept. If you have a look at the kubernetes one, you'll see it renders the objects like this in the values.yaml, when you select them all:

```
#local config for objects chart
splunk-kubernetes-objects:
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-objects
  kubernetes:
    insecureSSL: true
    clusterName: MicroK8s
  objects:
    core:
      v1: [{"name":"pods", "interval":"60s"},{"name":"nodes", "interval":"60s"},{"name":"component_statuses", "interval":"60s"},{"name":"config_maps", "interval":"60s"},{"name":"namespaces", "interval":"60s"},{"name":"persistent_volumes", "interval":"60s"},{"name":"persistent_volume_claims", "interval":"60s"},{"name":"resource_quotas", "interval":"60s"},{"name":"services", "interval":"60s"},{"name":"service_accounts", "interval":"60s"},{"name":"events", "mode":"watch"},]
    apps:
      v1:
        [{"name":"daemon_sets", "interval":"60s"},{"name":"deployments", "interval":"60s"},{"name":"replica_sets", "interval":"60s"},{"name":"stateful_sets", "interval":"60s"},]
  splunk:
    hec:
      indexName: em_meta
```


https://github.com/splunk/splunk-connect-for-kubernetes/blob/20e67c6f2dcf4d06f6efc7cc6763126946a6956f/helm-chart/splunk-connect-for-kubernetes/values.yaml#L492-L546
