### ISSUE TITLE
allow user to disable an @include to enable use case control

### ISSUE THREAD

**Issue by matthewmodestino** [splunk/splunk-connect-for-kubernetes#386]
<

**What would you like to be added**:

```
  # This is can be used to exclude verbose logs including various system and Helm/Tiller related logs.
  fluentd:
    # path of logfiles, default /var/log/containers/*.log
    path: /var/log/containers/*.log
    # paths of logfiles to exclude. object type is array as per fluentd specification:
    # https://docs.fluentd.org/input/tail#exclude_path
    exclude_path:
    #  - /var/log/containers/kube-svc-redirect*.log
    #  - /var/log/containers/tiller*.log

```

I would like the values.yaml to allow me to control the `@include` blocks to allow a user to easily enable/disable out of the box content. The charts we designed to be modular in this pattern. 

https://github.com/splunk/splunk-connect-for-kubernetes/blob/ddba2d21dc5c6af87243fd71b51d5afec963bff4/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L11-L20

For example, a user of the logging pod could ensure, container logs, journald, audit log, are controled by simply enabling or disabling the include blocks. 

**Why is this needed**:

Ease of management and use. we are seeing more users who may not need the entire SCK deploy, and may want to pare down or simplify the deployment.
