### ISSUE TITLE
Service account creation in 1.4.1 not gated by boolean

### ISSUE THREAD

**Issue by pc-mreeves** [splunk/splunk-connect-for-kubernetes#400]
**What happened**:
In our values override file we have this set:
```
serviceAccount:
  create: false
  name: splunk-system
```
**What you expected to happen**:
I expect the service account creation to be skipped and it to use the one I specified.

**How to reproduce it (as minimally and precisely as possible)**:
If you compare the service account template in 1.3.0 to 1.4.1
https://github.com/splunk/splunk-connect-for-kubernetes/blob/release/1.3.0/helm-chart/splunk-kubernetes-logging/templates/serviceAccount.yaml
to
https://github.com/splunk/splunk-connect-for-kubernetes/blob/release/1.4.1/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/serviceAccount.yaml
you can see the SA is always created event though documentation implies this can be controlled as I have described above:
https://github.com/splunk/splunk-connect-for-kubernetes/blob/master/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml#L93

I will make a PR to fix this if that's OK.
IIUC all I need to do is add `{{- if .Values.serviceAccount.create -}}` to top of 
https://github.com/splunk/splunk-connect-for-kubernetes/blob/release/1.4.1/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/serviceAccount.yaml

**Anything else we need to know?**:
nope.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version:
- Others:

**Comment by rockb1017** [comment]
Hello, 
starting from 1.4.0, service account is required for logging, because it needs to query from kubernetes API server and enrich the data.

**Comment by chaitanyaphalak** [comment]
@pc-mreeves are you using your own service account and using the helm chart with "create: false"?
In that case if its not working, it might be a bug.

**Comment by chaitanyaphalak** [comment]
also https://github.com/splunk/splunk-connect-for-kubernetes/issues/397

**Comment by pc-mreeves** [comment]
Correct. That is what I am saying. The docs indicate that we can provide a service account but this helm chart ignores that and creates it anyways. 

from links above.
1.3.0 behavior:
https://github.com/splunk/splunk-connect-for-kubernetes/blob/release/1.3.0/helm-chart/splunk-kubernetes-logging/templates/serviceAccount.yaml
```
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
{{ if .Values.image.usePullSecret }}
imagePullSecrets:
- name: {{ .Values.image.pullSecretName }}
{{ end }}
kind: ServiceAccount
metadata:
  name: {{ template "splunk-kubernetes-logging.serviceAccountName" . }}
  labels:
    app: {{ template "splunk-kubernetes-logging.name" . }}
    chart: {{ template "splunk-kubernetes-logging.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}
```

1.4.1 splunk-kubernetes-logging behavior:
https://github.com/splunk/splunk-connect-for-kubernetes/blob/release/1.4.1/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/serviceAccount.yaml
```
apiVersion: v1
{{ if .Values.image.usePullSecret }}
imagePullSecrets:
- name: {{ .Values.image.pullSecretName }}
{{ end }}
kind: ServiceAccount
metadata:
  name: {{ template "splunk-kubernetes-logging.serviceAccountName" . }}
  labels:
    app: {{ template "splunk-kubernetes-logging.name" . }}
    chart: {{ template "splunk-kubernetes-logging.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
```

this splunk-kubernetes-metrics chart for instance does not have this issue:
https://github.com/splunk/splunk-connect-for-kubernetes/blob/release/1.4.1/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/serviceAccount.yaml

```
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
{{ if .Values.image.usePullSecret }}
imagePullSecrets:
- name: {{ .Values.image.pullSecretName }}
{{ end }}
kind: ServiceAccount
metadata:
  name: {{ template "splunk-kubernetes-metrics.serviceAccountName" . }}
  labels:
    app: {{ template "splunk-kubernetes-metrics.name" . }}
    chart: {{ template "splunk-kubernetes-metrics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}
```
