### ISSUE TITLE
Optimize fluentd buffers and guidance

### ISSUE THREAD

**Issue by matthewmodestino** [splunk/splunk-connect-for-kubernetes#425]
**What would you like to be added**:

The Fluentd buffers should be optimized and guidance and simple test results should be shared. 

https://github.com/splunk/splunk-connect-for-kubernetes/blob/e680eb1d6fe53c0346ad66ddb22b3d8ee0703226/helm-chart/splunk-connect-for-kubernetes/values.yaml#L635-L643

```
  buffer:
    "@type": memory
    total_limit_size: 600m
    chunk_limit_size: 10m
    chunk_limit_records: 10000
    flush_interval: 3s
    flush_thread_count: 1
    overflow_action: block
    retry_max_times: 5
    retry_type: periodic

```
**Why is this needed**:

```chunk_limit_size``` has tested best at 10-20MB in high volume environments when customers have been doing scale/tress tests, plus we want to keep thruput high and chunk size low! We should try never to be sending a payload that big. 

```retry_type``` keeps us away from fluentd's exponential backoff timer, which can cause fun lag issues. We should lean to always firing out data as fast as we can. dont want to be holding buffers. Saw an instance where after failed attempts fluentd would wait 24 hours to send

**Comment by cheneysplunk** [comment]
Good points! 
May I ask what's the perf bottleneck of your system? fluentd or splunk? As perf perspective, the best practice may vary in different cases.
If the bottleneck is Splunk, yes I think we can use small `chunk_limit_size` but exponential backoff retry - this is recommended by Splunk HEC and implemented in many other Addons; However, if the bottleneck is fluentd, bigger `chunk_limit_size` can reduce the communication cost, and periodic retry is better.
Thanks for raising these questions. I think we can verify and then document them in future release.

**Comment by matthewmodestino** [comment]
Bottleneck is almost always network or Splunk side (indexing pipeline optimizations/config or intermediate forwarding and Load Balance tuning)

These settings are from my work with customers in the wild when they stress test us before use.

Similar results in On-prem OpenShift and Azure k8s, where reducing chunk size and adjustung retries reduced lag (_time vs index_time ) 

Happy to help set up the test use cases or re-create if the team wants!

**Comment by cheneysplunk** [comment]
Thanks for your info. @rockb1017  will follow up

**Comment by vinzent** [comment]
The current default in values.yml  is using `retry_max_times` of 5 with 1 second `retry_wait` (default according fluentd manual). This gives 5 seconds until the chunk is discarded and logs are lost.

https://github.com/splunk/splunk-connect-for-kubernetes/blob/79d17645af594762c9421cc184d59201a7ccb0a6/helm-chart/splunk-connect-for-kubernetes/values.yaml#L373-L382

So if you are in a situation where you have a network issue on the path from fluentd to splunk server you loose logs in almost no time.

**Comment by matthewmodestino** [comment]
You're right, retry should wait like 30 sec probably. We saw the lower retries cause trouble with Splunk Cloud too. retry should be periodic but give at least 30 sec (hec backoff tells client to try again later when saturated, for example.

**Comment by vinzent** [comment]
the current defaults also prevent the slow flush threshold (default: 20s) warning  ever to kick in due to discarding the chunk much earlier.

I think a sane default retry value would be something that tries to prevent loosing logs.

something like: 

```
retry_forever: true
retry_type: exponential_backoff
retry_wait: 1s
retry_max_interval: 60s
```

retry after 1,2,4,8,16,32 and then every 60 seconds. 

Regarding `@type: memory` : the logs already moved to buffer will be lost once something kills (or restarts) the fluentd pod . there should IMHO at least be a concrete example on how to configure a file backed buffer.

**Comment by matthewmodestino** [comment]
periodic was added cause customers didn't like the math in exponential backoff...it can lead fluentd to wait an entire day before retrying a chunk. I think you nailed it, we just need explicit retry wait rather than default 1s.

I suggest simply starting with a long retry interval. 60s sounds reasonable.

**Comment by vinzent** [comment]
having set the `retry_max_interval` to something reasonable should workaround the silly 1d retry wait intervals seen with default config and also cope with very short issues better than just a periodic 60s wait time.

**Comment by johnr84** [comment]
@vinzent we had some network/splunk side issue and wanted to tune the fluentd config to avoid loosing logs. Below is the config that I am planning to use. Do you think this is a good config or any recommendations? Plan is to wait for approx. 12 hourse(retry_max_times: 720). 

```
buffer:
    "@type": memory
    total_limit_size: 1000m
    chunk_limit_size: 20m
    chunk_limit_records: 100000
    flush_interval: 5s
    flush_thread_count: 1
    overflow_action: block
    retry_type: exponential_backoff
    retry_timeout: 72h
    retry_forever: false
    retry_max_times: 720
    retry_wait: 1s
    retry_max_interval: 60s
```
