### ISSUE TITLE
metrics-Agg typo: imagePullSecret instead of imagePullSecrets in deploymentMetricsAggregator.yaml

### ISSUE THREAD

**Issue by druesendieb** [splunk/splunk-connect-for-kubernetes#429]
**What happened**:
If you use an imagePullSecret for the metricsAgg deployment, helm creates invalid YAML.

Created YAML:
(obtained through `helm template` to analyse)

`splunk-kubernetes-metrics/deploymentMetricsAggregator.yaml`
```
      imagePullSecret:
      - name: SECRETNAME
```
**What you expected to happen**:
Create valid YAML

`splunk-kubernetes-metrics/deploymentMetricsAggregator.yaml`
```
      imagePullSecrets:
      - name: SECRETNAME
```
**How to reproduce it (as minimally and precisely as possible)**:
Used Settings
```
splunk-kubernetes-metrics:
  imageAgg:
(...)
    # Indicates if the image should be pulled using authentication from a secret
    usePullSecret: true
    # The name of the pull secret to attach to the respective serviceaccount used to pull the image
    pullsecretName: SECRETNAME
```

**Anything else we need to know?**:
PullRequest #430  

**Environment**:
SCK: 1.4.2
