### ISSUE TITLE
Error: certificate verify failed (unspecified certificate verification error)

### ISSUE THREAD

**Issue by ampaldhikar** [splunk/splunk-connect-for-kubernetes#442]
We are using a CA self signed certificate on our HEC Endpoint. Out set up for ingestion of Container logs is:
EKS  ------> Classic Load Balancer (AWS) ------> Splunk HF  ---> Splunk Indexers
This ingestion works perfectly fine without certificates over HTTP.

However, when I add a CA self signed cert on the LB, we are receiving the error "error: certificate verify failed (unspecified certificate verification error)"
I am using insecureSSL=false and have also added the certificates to the values.yaml file while setting up Splunk Connect for K8s.

When I remove the certs from the values.yaml file and still keep insecureSSL=false, I get this error:
"state=error: certificate verify failed (self signed certificate in certificate chain)"

Does the insecureSSL=false flag validate the certificate based on the Common Name and the CA within the cert?

**Comment by zencircle** [comment]
I am getting the similar error
`2020-12-08 21:22:42 +0000 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2020-12-08 21:22:43 +0000 chunk="5b5fa8a8d952a78f1e21b52be7b69cd9" error_class=OpenSSL::SSL::SSLError error="SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)"`
```
global:
  logLevel: info
  splunk:
    hec:
      # host is required and should be provided by user
      host: XXX
      port: 8088
      token: XXXX
      protocol: https
      indexName:
      insecureSSL: true
      clientCert:
      clientKey:
      caFile: XXX
```
