### ISSUE TITLE
Cannot execute fluentd in container version 1.1.4

### ISSUE THREAD

**Issue by CamillaBLarsen** [splunk/splunk-connect-for-kubernetes#446]
**What happened**:
/usr/bin/container-entrypoint: line 2: /fluentd/etc/fluent.conf: Permission denied
/usr/bin/container-entrypoint: line 2: exec: /fluentd/etc/fluent.conf: cannot execute: Permission denied
Can be fixed with a rw + x for anonymous on the configmap.
Following errors appear afterwards.
/fluentd/etc/fluent.conf: line 2: syntax error near unexpected token `newline'
/fluentd/etc/fluent.conf: line 2: `<system>'

**What you expected to happen**:
Running version 1.1.2 is working fine, but the new image fails to start.
All config and setup on the k8s cluster is as described in the manifest.
Using previous fluentd.conf file, as no changes from 1.1.2 -> 1.1.4 has been committed.

**How to reproduce it (as minimally and precisely as possible)**:
Run the container 1.1.2 with the specified configmap and secret on k8s.
Upgrade to image 1.1.4.

**Environment**:
- Image
docker.io/splunk/kube-objects:1.1.4
- Kubernetes version (use `kubectl version`):
1.17.9
- Ruby version (use `ruby --version`):
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
- OS (e.g: `cat /etc/os-release`):
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
- Splunk version:
8.0

**Comment by matthewmodestino** [comment]
HI @CamillaBLarsen 

Can you tell us more about how you have deployed and post some of your configs to help provide some guidance?

**Comment by CamillaBLarsen** [comment]
Sure, I tried to upgrade from 1.1.2 -> 1.1.4 manually - not using helm to deploy but our own pipeline.
The deployment is a copy from the git repo.

**ClusterRole.yml:**
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: splunk-kubernetes-objects
  labels:
    app: splunk-kubernetes-objects
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - namespaces
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - watch
```

**ClusterRoleBinding.yml:**
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: splunk-kubernetes-objects
  labels:
    app: splunk-kubernetes-objects
roleRef:
  kind: ClusterRole
  name: splunk-kubernetes-objects
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: splunk-kubernetes-objects
  namespace: splunk
```

**ServiceAccount:**
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: splunk-kubernetes-objects
  namespace: splunk
  labels:
    app: splunk-kubernetes-objects
```

**ConfigMap fluentd:**
`# Do not log self
<match fluent.**>
  @type null
</match>

# Set log level to warn
<system>
  log_level warn
</system>

# Objects source log - ONLY events
<source>
  @type kubernetes_objects
  tag kube.objects.*
  api_version "v1"
  insecure_ssl false
<watch>
  resource_name events
</watch>
</source>

# Add clustername
<filter kube.**>
  @type record_transformer
  <record>
    cluster_name "#{ENV['CLUSTER_NAME']}"
  </record>
</filter>

<filter kube.**>
  @type jq_transformer
  # in ruby '\\' will escape and become just '\', since we need two '\' in the `gsub` jq filter, it becomes '\\\\'.
  jq '.record.source = "namespace:\(env.MY_NAMESPACE)/pod:\(env.MY_POD_NAME)" | .record.sourcetype = (.tag | gsub("\\\\."; ":")) | .record'
</filter>

# Send data to splunk
<match kube.**>
  @type splunk_hec
  protocol http
  hec_host "#{ENV['SPLUNK_HEC_HOST']}"
  hec_port 8088
  hec_token "#{ENV['SPLUNK_HEC_TOKEN']}"
  host "#{ENV['NODE_NAME']}"
  source_key source
  sourcetype_key sourcetype
  index "#{ENV['SPLUNK_HEC_INDEX']}"
  insecure_ssl true
  <buffer>
    @type memory
    chunk_limit_records 10000
    chunk_limit_size 200m
    flush_interval 3s
    flush_thread_count 1
    overflow_action block
    retry_max_times 3
    total_limit_size 600m
  </buffer>
</match>`

**Comment by matthewmodestino** [comment]
check your deployment? looks like perhaps user/perms issues with fluentd and the config. 

I would recommend using `helm template` to generate manifests from the latest values.yaml to help test.

**Comment by CamillaBLarsen** [comment]
The manifest in the repo, our config files are modified from that source.

The permissions issues can be resolved with a 777 mask.
But then it still fails to parse the fluentd.conf ...
/fluentd/etc/fluent.conf: line 2: syntax error near unexpected token newline' /fluentd/etc/fluent.conf: line 2: '

And I assume that should parse correctly as long as the file is visible??

**Comment by matthewmodestino** [comment]
Have you edited the configmap?

Mine looks likes this, fwiw:

```
kubectl -n splunk-dev get cm sck-splunk-kubernetes-objects -o yaml
apiVersion: v1
data:
  fluent.conf: |
    <system>
      log_level warn
    </system>
    <source>
      @type kubernetes_objects
      tag kube.objects.*
      api_version "apps/v1"
      insecure_ssl true
      <pull>
        resource_name daemon_sets
        interval 60s
      </pull>
      <pull>
        resource_name deployments
        interval 60s
      </pull>
      <pull>
        resource_name replica_sets
        interval 60s
      </pull>
      <pull>
        resource_name stateful_sets
        interval 60s
      </pull>
    </source>
    <source>
      @type kubernetes_objects
      tag kube.objects.*
      api_version "v1"
      insecure_ssl true
      <pull>
        resource_name pods
        interval 60s
      </pull>
      <pull>
        resource_name nodes
        interval 60s
      </pull>
      <pull>
        resource_name component_statuses
        interval 60s
      </pull>
      <pull>
        resource_name config_maps
        interval 60s
      </pull>
      <pull>
        resource_name namespaces
        interval 60s
      </pull>
      <pull>
        resource_name persistent_volumes
        interval 60s
      </pull>
      <pull>
        resource_name persistent_volume_claims
        interval 60s
      </pull>
      <pull>
        resource_name resource_quotas
        interval 60s
      </pull>
      <pull>
        resource_name services
        interval 60s
      </pull>
      <pull>
        resource_name service_accounts
        interval 60s
      </pull>
      <watch>
        resource_name events
      </watch>
    </source>

    <filter kube.**>
      @type jq_transformer
      # in ruby '\\' will escape and become just '\', since we need two '\' in the `gsub` jq filter, it becomes '\\\\'.
      jq '.record.source = "namespace:\(env.MY_NAMESPACE)/pod:\(env.MY_POD_NAME)" | .record.sourcetype = (.tag | gsub("\\\\."; ":")) | .record'
    </filter>

    <filter kube.**>
      @type jq_transformer
      jq '.record.cluster_name = "MicroK8s" | .record'
    </filter>

    # = custom filters specified by users =

    <match kube.**>
      @type splunk_hec
      protocol https
      hec_host "splunk-mattymo"
      hec_port 8088
      hec_token "#{ENV['SPLUNK_HEC_TOKEN']}"
      host "#{ENV['NODE_NAME']}"
      source_key source
      sourcetype_key sourcetype
      index em_meta
      insecure_ssl true
      <fields>
        cluster_name
      </fields>
      <buffer>
        @type memory
        chunk_limit_records 10000
        chunk_limit_size 20m
        flush_interval 5s
        flush_thread_count 1
        overflow_action block
        retry_max_times 5
        retry_type periodic
        total_limit_size 600m
      </buffer>
    </match>
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: sck
    meta.helm.sh/release-namespace: splunk-dev
  creationTimestamp: "2020-08-25T22:49:58Z"
  labels:
    app: splunk-kubernetes-objects
    app.kubernetes.io/managed-by: Helm
    chart: splunk-kubernetes-objects-1.4.3
    heritage: Helm
    release: sck
  name: sck-splunk-kubernetes-objects
  namespace: splunk-dev
  resourceVersion: "46082912"
  selfLink: /api/v1/namespaces/splunk-dev/configmaps/sck-splunk-kubernetes-objects
  uid: 6c128e47-da11-493e-b44e-8479031d0d9f
```

**Comment by CamillaBLarsen** [comment]
I tried to modify it - but haven't run an entire new config file.

I can try to test with your version, see if that parses correctly :)
Thanks for the assistance.

**Comment by matthewmodestino** [comment]
cool let us know if its still brokey after render with the latest charts.

**Comment by CamillaBLarsen** [comment]
A replacement of the fluentd config didn't work.

/fluentd/etc/fluent.conf: line 1: syntax error near unexpected token `newline'
/fluentd/etc/fluent.conf: line 1: `<system>'

I will try to create new charts with helm.

**Comment by matthewmodestino** [comment]
Here's my latest run (you can update your chart name and namespace accordingly):

```
mkdir sck-render
mmodestino-mbp-2bc70:sck mmodestino$ helm template -n splunk-dev sck -f sck-values-143.yaml https://github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.4.3/splunk-connect-for-kubernetes-1.4.3.tgz --output-dir sck-render
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/serviceAccount.yaml
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/serviceAccount.yaml
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/serviceAccount.yaml
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/secret.yaml
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/secret.yaml
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/secret.yaml
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/configMap.yaml
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/configMapMetricsAggregator.yaml
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/configMap.yaml
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/clusterRole.yaml
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/clusterRole.yaml
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/clusterRoleAggregator.yaml
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/clusterRole.yaml
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/clusterRoleBinding.yaml
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/clusterRoleBinding.yaml
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/clusterRoleBindingAggregator.yaml
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/clusterRoleBinding.yaml
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/daemonset.yaml
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/daemonset.yaml
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/deploymentMetricsAggregator.yaml
wrote sck-render/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/deployment.yaml
```

I use this `values.yaml` in my MicroK8s lab, so mileage may vary, you likely don't need all the things, but this serves as a good skeleton to play with

see `values.yaml` for the various charts for all settings


```
#global settings
global:
  logLevel: warn 
  splunk:
    hec:
      protocol: https
      insecureSSL: true 
      host: splunk-mattymo 
      token: "3A63B407-705F-CCD3-52DB-908EBA7F5CDB"
      port: 8088 


#local config for logging chart
splunk-kubernetes-logging:
  containers:
    logFormatType: cri
    logFormat: "%Y-%m-%dT%H:%M:%S.%N%:z"
  kubernetes:
    clusterName: MicroK8s
    securityContext: true 
  journalLogPath: /var/log/journal
  buffer:
    "@type": memory
    total_limit_size: 600m
    chunk_limit_size: 10m
    chunk_limit_records: 100000
    flush_interval: 2s
    flush_thread_count: 1
    overflow_action: block
    retry_max_times: 10
    retry_type: periodic
  k8sMetadata:
  # Pod labels to collect
    podLabels:
      - app
      - k8s-app
      - release
  splunk:
    hec:
      indexName: em_events
  logs:
    #nginx-ingress:
    #  from:
    #    pod: nginx-ingress
    #    container: nginx-ingress-controller
    #  #keep default sourcetype for sake of avoiding complexity
    #  #if you really want to customize sourcetype you can 
    #  sourcetype: nginx:ingress:controller
    #  multiline:
    #    firstline: /^\w[0-1]\d[0-3]\d\s\d{2}:\d{2}:\d{2}.\d{6}\s|^\d+\.\d+\.\d+\.\d+[^\[]+|\d{4}\/\d{2}\/\d{2}\s\d{2}:\d{2}:\d{2}[^\[]+|^NGINX\sIngress\scontroller|^----------/
    sck:
      from:
        pod: sck-splunk-kubernetes-
        container: splunk-fluentd-k8s-
      multiline:
        firstline: /^\d{4}-\d{2}-\d{2}\s\d{2}\:\d{2}\:\d{2}\s\+\d{4}\s\[\w+\]\:/
        separator: "\n"
        flushInterval: 2
    ghost:
      from:
        pod: ghost
        container: ghost
      multiline:
        firstline: /^\[\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\]/
        separator: "\n"
        flushInterval: 2
    mario:
      from:
        pod: mattymo-mario
        container: docker-supermario
      multiline: 
        firstline: /NOTE\:\sPicked\sup\sJDK_JAVA_OPTIONS\:|\d{2}\-\w+\-\d{4}\s\d{2}:\d{2}:\d{2}\.\d{3}\s\w+\s\[/ 
        separator: "\n"
        flushInterval: 2
    
#local config for objects chart
splunk-kubernetes-objects:
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-objects
  kubernetes:
    insecureSSL: true
    clusterName: MicroK8s
  objects:
    core:
      v1: [{"name":"pods", "interval":"60s"},{"name":"nodes", "interval":"60s"},{"name":"component_statuses", "interval":"60s"},{"name":"config_maps", "interval":"60s"},{"name":"namespaces", "interval":"60s"},{"name":"persistent_volumes", "interval":"60s"},{"name":"persistent_volume_claims", "interval":"60s"},{"name":"resource_quotas", "interval":"60s"},{"name":"services", "interval":"60s"},{"name":"service_accounts", "interval":"60s"},{"name":"events", "mode":"watch"},]
    apps:
      v1:
        [{"name":"daemon_sets", "interval":"60s"},{"name":"deployments", "interval":"60s"},{"name":"replica_sets", "interval":"60s"},{"name":"stateful_sets", "interval":"60s"},]
  splunk:
    hec:
      indexName: em_meta

#local config for metrics chart
splunk-kubernetes-metrics:
  metricsInterval: 60s
  kubernetes:
    kubeletPort: 10255
    kubeletPortAggregator: 10250
    useRestClientSSL: false
    insecureSSL: true
    clusterName: MicroK8s
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-metrics
  splunk:
    hec:
      indexName: em_metrics

#App for Infra Dimensions for K8s
  customFilters:
    node:
      tag: "kube.node.**"
      type: record_modifier
      body: |-
        <record>
          entity_type k8s_node
        </record>
    pod:
      tag: "kube.pod.**"
      type: record_modifier
      body: |-
        <record>
          entity_type k8s_pod
        </record>
```
