### ISSUE TITLE
Support for Windows Server 2019 Nodes

### ISSUE THREAD

**Issue by matthewmodestino** [splunk/splunk-connect-for-kubernetes#455]
**What would you like to be added**:

Review support for Windows containers running on Windows Server 2019, as it is now supported by k8s. 

**Why is this needed**:

To support windows/.net shops who are likely to adopt more now that it is supported in EKS, AKS etc.

**Comment by matthewmodestino** [comment]
https://github.com/splunk/fluent-plugin-splunk-hec/pull/64/files

**Comment by cheneysplunk** [comment]
Thanks Matthew. This Jira is created for this requirement. Will let our PM know. https://jira.splunk.com/browse/ADDON-29335

**Comment by matthewmodestino** [comment]
```
     containers:
      - name: fluentd-windows
        image: bgsilvait/winfluentd:1809
        env:
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: fluentd-windows
                key: AWS_REGION
          - name: CLUSTER_NAME
            valueFrom:
              configMapKeyRef:
                name: fluentd-windows
                key: CLUSTER_NAME
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
        volumeMounts:
        - name: fluentdconftemp
          mountPath: /etc/temp/
        - name: fluentdconf
          mountPath: /etc/fluent
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: C:\ProgramData\Docker\containers
          readOnly: true
```
