### ISSUE TITLE
Add RKE support for logging component

### ISSUE THREAD

**Issue by sugarraysam** [splunk/splunk-connect-for-kubernetes#490]
Hello Splunk fellows!

We have been experimenting with this app at my company, and I wanted to share some feedback as I have seen many issues on this. We are using RKE (rancher) to spin our cluster and this causes problem when it comes to the logging component.

## What we need to collect:
1. `/var/logs/containers/*.log` - (which are symlinks to `/var/lib/docker/containers/**`)
2. journald `docker.service` unit
3. `/var/lib/rancher/rke/log/*.log`

Now 1 & 2 work fine, but when we try to make it work with 3, we get problems. The main issue is, the application can only have 2 mountpoints, and does not support adding a 3rd mount point, in this case `/var/lib/rancher/rke/log`.

```yaml
# Mounts those two folders, so we can resolve the symlinks from /var/log/containers or /var/log/pods
containers:
  path: /var/log
  pathDest: /var/lib/docker/containers

# Mounts this for journald
journalLogPath: /var/log/journal

```

To work around the missing 3rd mount point, I tried hacking this thing in a couple of ways:

## Solution 1 - Do two deployments of SCK

The idea is to deploy the SCK app twice:
1. First deployment has `metrics` + `objects` enabled, and scrapes containers normally:
```yaml
fluentd: 
  path: /var/log/containers/*.log
containers:
  path: /var/log
  pathDest: /var/lib/docker/containers
```

2. Second deployment has `metrics` + `objects` disabled, and scrapes `/var/lib/rancher/rke/log`:
```yaml
fluentd: 
  path: /var/lib/rancher/rke/log/*.log
containers:
  path: /var/lib/rancher/rke/log/
  pathDest: /var/lib/docker/containers
```

**Problem - log enrichment fails**

SCK tries to do log enrichment on the RKE logs. RKE deploys those as bare containers, that don't have associated pod or objects in the k8s cluster. They live "outside" of the cluster, as stand-alone containers. And so, fluentd fails with: __record.dig error no implicit conversion of nil into String__, because record.dig does not find anything. (closed issue -> #439)

## Solution 2 - mount `/var/lib/rancher/rke/log` as `journalLogPath`

This is our current solution, which is not perfect and hakish:

```yaml
fluentd: 
  path: /var/log/containers/*.log
containers:
  path: /var/log
  pathDest: /var/lib/docker/containers

# This will mount the rancher core k8s logs, at the cost of not having access to journald logs
journalLogPath: /var/lib/rancher/rke/log
```

**Problem - cant ingest `docker.service`**

As `journalLogPath` is not a journald path, we cant ingest system unit logs from journald.

**Problem - core k8s components ingested as files**

Core k8s components living in `/var/lib/rancher/rke/log/*.log` are logs which have the same format as normal docker containers. But in this case, since log enrichment fails, we have to ingest them as files, which is not ideal and does not use the full power of fluentd + jq + json parsing:

```yaml
logs:
  etcd:
    from:
      file:
        path: /var/lib/rancher/rke/log/etcd*.log
    timestampExtraction:
      regexp: (?<time>\d{4}-\d{2}-\d{2}T[0-2]\d:[0-5]\d:[0-5]\d.\d{9}Z)
      format: "%Y-%m-%dT%H:%M:%S.%NZ"
    sourcetype: kube:etcd
```

And also, I get so many errors/warnings doing this:
![image](https://user-images.githubusercontent.com/20143605/97454901-3fbfd700-1905-11eb-8be9-1e0400eb0a7f.png)

I have not found a way to correctly ingest those as files, and I don't think we should. The appropriate solution is to be able to ingest those extra logs, as json, like normal containers, but without enrichment.

**What would you like to be added**:

- Be able to ingest RKE logs located at `/var/lib/rancher/rke/log` as normal json containers, without enrichment
- Make `read_from_head <bool>` configurable (from `configMap.yaml`)

This is set to `true` by default and will cause huge CPU spikes on first SCK deploy. Most people deploy this as an **after the fact** app, and so the history of log can be quite huge and we don't really care about those.

**Why is this needed**:

A lot of folks deploy their cluster using RKE/Rancher. This would be a useful feature.
