### ISSUE TITLE
splunk-heapster cannot connect to splunk-fluentd-heapster

### ISSUE THREAD

**Issue by voki** [splunk/splunk-connect-for-kubernetes#50]
Hi,

I am getting error in metrics pod, looks like one container is unable to connect to other inside same pod.
I have installed connector from Helm chart, version 1.0.1.

splunk-heapser container logs:
I1122 11:53:58.124170       1 heapster.go:78] /heapster --source=kubernetes --sink=statsd:udp://127.0.0.1:9001
I1122 11:53:58.124207       1 heapster.go:79] Heapster version v1.5.1
I1122 11:53:58.124437       1 configs.go:61] Using Kubernetes client with master "https://10.96.0.1:443" and version v1
I1122 11:53:58.124449       1 configs.go:62] Using kubelet port 10255
I1122 11:53:58.140256       1 driver.go:104] statsd metrics sink using configuration : {host:127.0.0.1:9001 prefix: numMetricsPerMsg:5 protocolType:etsystatsd renameLabels:map[] allowedLabels:map[] customizeLabel:0x15f2560}
I1122 11:53:58.140281       1 driver.go:104] statsd metrics sink using configuration : {host:127.0.0.1:9001 prefix: numMetricsPerMsg:5 protocolType:etsystatsd renameLabels:map[] allowedLabels:map[] customizeLabel:0x15f2560}
I1122 11:53:58.140301       1 heapster.go:202] Starting with StatsD Sink
I1122 11:53:58.140305       1 heapster.go:202] Starting with Metric Sink
I1122 11:53:58.328875       1 heapster.go:112] Starting heapster on port 8082
E1122 11:54:06.526301       1 driver.go:159] **statsd metrics sink - failed to send some metrics : write udp 127.0.0.1:38104->127.0.0.1:9001: write: connection refused**

splunk-fluentd-heapster container logs, looks like it is listening:
2018-11-22 11:54:02 +0000 [info]: starting fluentd-1.2.0 pid=8 ruby="2.5.1"
2018-11-22 11:54:02 +0000 [info]: spawn command to main:  cmdline=["/usr/local/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/local/bundle/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "--under-supervisor"]
2018-11-22 11:54:06 +0000 [info]: gem 'fluent-plugin-concat' version '2.2.2'
2018-11-22 11:54:06 +0000 [info]: gem 'fluent-plugin-jq' version '0.5.1'
2018-11-22 11:54:06 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.0.1'
2018-11-22 11:54:06 +0000 [info]: gem 'fluent-plugin-splunk-hec' version '1.0.1'
2018-11-22 11:54:06 +0000 [info]: gem 'fluent-plugin-systemd' version '0.3.1'
2018-11-22 11:54:06 +0000 [info]: gem 'fluentd' version '1.2.0'
2018-11-22 11:54:06 +0000 [info]: adding match pattern="raw.metrics.udp" type="jq"
2018-11-22 11:54:06 +0000 [info]: adding match pattern="metrics.udp" type="splunk_hec"
2018-11-22 11:54:07 +0000 [info]: adding source type="udp"
2018-11-22 11:54:07 +0000 [info]: #0 starting fluentd worker pid=16 ppid=8 worker=0
2018-11-22 11:54:07 +0000 [info]: #0 listening udp socket bind="0.0.0.0" port=9001
2018-11-22 11:54:07 +0000 [info]: #0 fluentd worker is now running worker=0

Any idea what might be wrong?

Thanks.

**Comment by matthewmodestino** [comment]
Hi voki!

The metrics pod contains two containers, one for heapster, the other for fluentd. 

Looks like the heapster container cant reach fluent on 9001?

**Comment by voki** [comment]
Hi, exactly, two containers in one pod. As you can see in logs fluent is listening on 9001.
I can see logs in devops index, but devops_metrics is empty, because of that error.
My custom helm values:

global:
  splunk:
    hec:
      token: <devops_token>
      host: <IP>
      port: 8088
      indexName: devops
      # connection to splunk is insecure
      insecureSSL: true


splunk-kubernetes-objects:
  # RBAC is disabled
  rbac:
    create: true

  serviceAccount:
    create: true

  kubernetes:
      # connection to kubernetes is insecure
      insecureSSL: true


splunk-kubernetes-metrics:
  # RBAC is disabled
  rbac:
    create: true

  # do not create service account
  serviceAccount:
    create: true

  splunk:
    hec:
      token: <devops_metrics_token>
      host: <IP>
      port: 8088
      indexName: devops_metrics
      # connection to splunk is insecure
      insecureSSL: true

**Comment by matthewmodestino** [comment]
what version of kubernetes are you running on?

**Comment by voki** [comment]
v1.12.2

**Comment by matthewmodestino** [comment]
I just battled heapster deployment on 1.11, I ended up creating my own clusterRoleBinding that gave the service account `cluster-admin`, then changed the deployment manifest to point to:

```
  spec:
      serviceAccountName: splunk-kubernetes-metrics
      containers:
      - image: k8s.gcr.io/heapster-amd64:v1.5.1
        imagePullPolicy: IfNotPresent
        name: splunk-heapster
        command:
        - "/heapster"
        #--source=kubernetes"
        - "--source=kubernetes:https://kubernetes.default.svc?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250&insecure=true"
        - "--sink=statsd:udp://127.0.0.1:9001
```

no sure if that will help here, but I would just make sure that heapster is even pointed in the right direction, as the kubelet's configs have changed.

**Comment by matthewmodestino** [comment]
Ok, jump on one of your nodes and check where the kublet is serving. 


```
root@ip-10-0-18-126:/etc/kubernetes/manifests# cat /var/lib/kubelet/config.yaml | grep port
port: 10250
```

You can also check:

**Comment by voki** [comment]
Kubelet port is 10250.
I have external secured etcd, also api server is secured and listening on port 6443.
From the logs, it looks like the problem is with connection inside the pod.
I have just created test pod with two containers, I was able to telnet from one to another on 127.0.0.1.
At least I know it's not network issue.

**Comment by voki** [comment]
Solved, I was installing Helm chart into custom namespace but service account was created by app in default one.
Metrics index is still empty though. Shouldn't there be some default metrics at least ?

**Comment by voki** [comment]
I have just deployed helm chart into default namespace, no updates to ports.
Below is the content of the custom helm values file that I have used:

```
splunk-kubernetes-logging:
  rbac:
    create: true

  serviceAccount:
    create: true

  splunk:
    hec:
      token: ***
      host: ***
      port: 8088
      indexName: devops
      insecureSSL: true

splunk-kubernetes-objects:
  rbac:
    create: true

  serviceAccount:
    create: true

  splunk:
    hec:
      token: ***
      host: ***
      port: 8088
      indexName: devops
      insecureSSL: true

  kubernetes:
      insecureSSL: true


splunk-kubernetes-metrics:
  rbac:
    create: true

  serviceAccount:
    create: true

  splunk:
    hec:
      token: ***
      host: ***
      port: 8088
      indexName: devops_metrics
      insecureSSL: true
```
