### ISSUE TITLE
clusterName and other metadata not appearing in Splunk

### ISSUE THREAD

**Issue by cedricmorandin** [splunk/splunk-connect-for-kubernetes#528]
**What happened**:
I am deploying the logging chart alone with minimalistic parameters.yaml including the clusterName and podLabels configurations. With this setup I correctly see the logs coming in Splunk but I can only filter by source, sourcetype, host and splunk_server but not clusterName.

**What you expected to happen**:
I assumed that I could filter by cluster or the value of the podLabels list in Splunk.

**How to reproduce it (as minimally and precisely as possible)**:
The helm chart is installed/updated with the following command line:
`helm upgrade splunk-logging -f parameters.yaml --create-namespace -n splunk https://github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.4.4/splunk-kubernetes-logging-1.4.4.tgz`

The following parameters.yaml is used:
```
splunk:
  hec:
    token: ****** 
    host:  ****** 
    port:  ****** 
    indexName: ****** 

fluentd:
  path: /var/log/containers/*.log
  exclude_path:
    - /var/log/containers/calico*.log
    - /var/log/containers/splunk-logging-splunk-kubernetes-logging*.log

containers:
  path: /var/log
  pathDest: /var/lib/docker/containers
  logFormatType: json

journalLogPath: /var/log/journal
  
k8sMetadata:
  podLabels:
    - app
    - role
  watch: true
  catch_ttl: 3600

kubernetes:
  clusterName: the-cluster-name-that-i-want 

podSecurityPolicy:
  create: true 
  apparmor_security: false

logs:
  myapp:
    from:
      pod: myapp-*
    multiline:
      firstline: /\d{4}-\d{1,2}-\d{1,2}/
```
**Anything else we need to know?**:
In the logs of the SCK I see the following warning messages when Fluentd is starting:
```
2021-01-07 11:57:17 +0000 [warn]: parameter 'cluster_name' in <fields>
  container_image 
  pod_uid 
  pod 
  container_name 
  namespace 
  container_id 
  cluster_name 
  label_app 
  label_client 
  label_role 
</fields> is not used.
2021-01-07 11:57:17 +0000 [warn]: parameter 'label_app' in <fields>
  container_image 
  pod_uid 
  pod 
  container_name 
  namespace 
  container_id 
  cluster_name 
  label_app 
  label_client 
  label_role 
</fields> is not used.
```

**Environment**:
- Kubernetes version (use `kubectl version`):
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version: 
- Splunk Connect for Kubernetes helm chart version: 1.4.4
- Others:
