### ISSUE TITLE
Not able to fetch logs in splunk, Server is busy, code:9 Invalid event number

### ISSUE THREAD

**Issue by dunefro** [splunk/splunk-connect-for-kubernetes#555]
**What happened**:
We are trying to fetch logs from kubernetes to pass them to splunk.  The following error comes up in the logging pods
```
2021-02-15 05:14:01 +0000 [warn]: #0 failed to flush the buffer. retry_time=3 next_retry_seconds=2021-02-15 05:14:02 +0000 chunk="5bb590d3789c6b8ee4a15d306b1d6ad2" error_class=RuntimeError error="Server error (503) for POST http://splunk.example.com:8088/services/collector, response: {\"text\":\"Server is busy\",\"code\":9,\"invalid-event-number\":0}"
  2021-02-15 05:14:01 +0000 [warn]: #0 suppressed same stacktrace
```

**What you expected to happen**:
Logs should be seen in the index `index_for_logs` index that we have configured.

**How to reproduce it (as minimally and precisely as possible)**:
1. We created HEC token  <token> for index `index_for_logs`.
2. We used the below values.yaml
```
global:
  splunk:
    hec:
      token: <token>
      host: splunk.example.com
      port: 8088
      indexName: index_for_logs
      # connection to splunk is insecure
      insecureSSL: true
  kubernetes:
    clusterName: "cluster_name"

splunk-kubernetes-logging:
  enabled: true
  splunk:
    hec:
      host: splunk.example.com
      port: 8088
      token: <token>
      protocol: http
      indexName: index_for_logs
      insecureSSL: true

splunk-kubernetes-objects:
  enabled: false

splunk-kubernetes-metrics:
  enabled: false
```

**Anything else we need to know?**:
Its a four node cluster with one master and 3 nodes.
```
kubectl get nodes
NAME         STATUS   ROLES    AGE   VERSION
***-master   Ready    master   30d   v1.18.8
***-node01   Ready    <none>   30d   v1.18.8
***-node02   Ready    <none>   30d   v1.18.8
***-node03   Ready    <none>   30d   v1.18.8
```
Command used to deploy the helm chart
```
helm install my-splunk-connect splunk-connect-for-kubernetes/ -f new.yaml
```
with new.yaml being the above values file
Status of the kubernetes pod
```
kubectl get pods -l "app=splunk-kubernetes-logging"
NAME                                                READY   STATUS    RESTARTS   AGE
my-splunk-connect-splunk-kubernetes-logging-6fv9m   1/1     Running   0          11m
my-splunk-connect-splunk-kubernetes-logging-6qghj   1/1     Running   0          11m
my-splunk-connect-splunk-kubernetes-logging-vtk9p   1/1     Running   0          11m
my-splunk-connect-splunk-kubernetes-logging-xj6g9   1/1     Running   0          11m

```
**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Splunk version:
```
8.1.1
```
- Splunk Connect for Kubernetes helm chart version:
```
apiVersion: v1
appVersion: 1.4.5
description: Collect logs, objects (metadata), and metrics with Splunk.
home: https://github.com/splunk/splunk-connect-for-kubernetes/tree/main/helm-chart
keywords:
- splunk
- monitoring
- logging
- metrics
- metadata
- objects
maintainers:
- email: DataEdge@splunk.com
  name: Splunk Inc.
name: splunk-connect-for-kubernetes
sources:
- https://github.com/splunk/splunk-connect-for-kubernetes/tree/main/helm-chart
- https://github.com/splunk/fluent-plugin-splunk-hec
- https://github.com/splunk/fluent-plugin-kubernetes-metrics
- https://github.com/splunk/fluent-plugin-k8s-metrics-agg
- https://github.com/splunk/fluent-plugin-kubernetes-objects
version: 1.4.5
```
- Others:
