### ISSUE TITLE
Installing splunk-connect with ansible helm module error

### ISSUE THREAD

**Issue by nmajin** [splunk/splunk-connect-for-kubernetes#566]
I know I might not get the proper support here for an ansible error, but I am curious if I am actually referencing the repo for this helm chart correctly:

```
    - name: Install splunk-connect
      helm:
        host: localhost
        chart:
          name: splunk-connect-for-kubernetes
          version: 1.4.6
          source:
            type: repo
            location: https://splunk.github.io/splunk-connect-for-kubernetes
        state: present
        name: splunk-connect-aks
        namespace: splunk
        values: "{{ lookup('file', 'values.yaml') | from_yaml }}"
```
The error below essentially state:
- failed to connect to all addresses
- Failed to pick subchannel

`
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "2021-02-24 21:46:19,641 - ChartBuilder - INFO - Cloning https://splunk.github.io/splunk-connect-for-kubernetes// for release splunk-connect-for-kubernetes\nTraceback (most recent call last):\n  File \"/users/<user>/.ansible/tmp/ansible-tmp-1614221178.96-55127641241215/AnsiballZ_helm.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/users/<user>/.ansible/tmp/ansible-tmp-1614221178.96-55127641241215/AnsiballZ_helm.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/users/<user>/.ansible/tmp/ansible-tmp-1614221178.96-55127641241215/AnsiballZ_helm.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_helm_payload_7LznPH/__main__.py\", line 184, in <module>\n  File \"/tmp/ansible_helm_payload_7LznPH/__main__.py\", line 172, in main\n  File \"/tmp/ansible_helm_payload_7LznPH/__main__.py\", line 104, in install\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyhelm/tiller.py\", line 114, in list_releases\n    for y in release_list:\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/grpc/_channel.py\", line 413, in next\n    return self._next()\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/grpc/_channel.py\", line 803, in _next\n    raise self\ngrpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses\"\n\tdebug_error_string = \"{\"created\":\"@1614221182.847191671\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":5391,\"referenced_errors\":[{\"created\":\"@1614221182.847189285\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc\",\"file_line\":398,\"grpc_status\":14}]}\"\n>\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
        to retry, use: --limit @/home/<user>/test.retry
`
