### ISSUE TITLE
splunk-logging not able to ingest container logs using default and custom values.yaml for GKE

### ISSUE THREAD

**Issue by kurinei021** [splunk/splunk-connect-for-kubernetes#581]
Hi, Support Team,

After the implementation of splunk-logging deployment in Google Kubernetes, the Splunk dashboard was not showing container logs for any pods running in the cluster.

**What happened:**

We can see metrics and objects being ingested, unfortunately for the container logs, it is missing.

**Environment:**

Splunk Connect for Kubernetes helm chart version: 1.4.6

**Comment by kurinei021** [comment]
**for custom values.yaml file:**

```
global:
  splunk:
    hec:
      protocol: https
      insecureSSL: true
      token: xxxxxxxxxxxxxxxxxxxxxx
      host: 10.xx.xx.xx
      port: 8088
      indexName: events

fluentd:
  path: /var/log/containers/*.log
  exclude_path:
   - /var/log/containers/newrelic-infra*.log
   - /var/log/containers/cert*.log
   - /var/log/containers/newrelic*.log
   - /var/log/containers/nri*.log
   - /var/log/containers/stackdriver*.log
   - /var/log/containers/gke*.log
   - /var/log/containers/splunk*.log
   - /var/log/containers/metrics*.log
   - /var/log/containers/l7*.log
   - /var/log/containers/istio*.log
   - /var/log/containers/promsd*.log
   - /var/log/containers/rest2ldap*.log
   - /var/log/containers/fluent*.log
   - /var/log/containers/laughing*.log
   - /var/log/containers/kube*.log
   - /var/log/containers/calico*.log
   - /var/log/containers/netd*.log
   - /var/log/containers/load*.log
   - /var/log/containers/alertmanager*.log
   - /var/log/containers/prometheus*.log
   - /var/log/containers/tiller*.log
   
splunk-kubernetes-metrics:
  enabled: false

splunk-kubernetes-objects:
  enabled: false
```
