### ISSUE TITLE
How to forward audit logs to its own event index?

### ISSUE THREAD

**Issue by catherinelam** [splunk/splunk-connect-for-kubernetes#600]
There's a similar issue: https://github.com/splunk/splunk-connect-for-kubernetes/issues/94

But what I'm trying to do is forward audit logs, not just kube api logs. The audit logs don't belong to a container itself. Is there a way to filter that to its own bucket?

**Comment by skirven4** [comment]
Hi! Is it something like this you're looking for?

```
  kube-audit:
    from:
      file:
        path: /var/log/kube-audit/audit-log.json
    timestampExtraction:
      format: "%Y-%m-%dT%H:%M:%SZ"
    sourcetype: paas:rancher-audit-logs 
```
You would need to use your props.conf and transforms.conf to forward the data to another index if you aren't wanting to use the default one from the YAML file.
Hope that helps!
Stephen
