### ISSUE TITLE
"pattern not matched" error in Splunk connect logging pods

### ISSUE THREAD

**Issue by abudavis** [splunk/splunk-connect-for-kubernetes#604]
We have deployed Splunk Connect for Kubernetes on Openshift 4.6 using helm and are getting the below error in the logging pods.
Please let us know how to fix this.

`2021-04-22 08:31:34 +0000 [warn]: #0 [containers.log] pattern not matched: "2021-04-22T08:31:17.647698673+00:00 stdout P 2021-04-22 08:31:17 +0000 [warn]: #0 [containers.log] pattern not matched: \"2021-04-22T08:31:08.789002238+00:00 stdout F \\\\\\\\\\\\\\\\\\\\\\\\\\\\\`

Reference bug: https://github.com/fluent/fluentd-kubernetes-daemonset/issues/434

Environment:
- Openshift 4.6.21
- Kubernetes version v1.19
- Splunk Connect for Kubernetes helm chart version: 1.4.7

**Comment by vinzent** [comment]
Please share your helm values.yaml that you used to deploy SCK. Be sure to remove credentials.

**Comment by abudavis** [comment]
helm values.yaml attached.[
[values-yaml.txt](https://github.com/splunk/splunk-connect-for-kubernetes/files/6356920/values-yaml.txt)

](url)

**Comment by abudavis** [comment]
Please find the values.yaml attached.
[values-yaml.txt](https://github.com/splunk/splunk-connect-for-kubernetes/files/6356932/values-yaml.txt)

**Comment by vinzent** [comment]
OpenShift 4.x logtype is cri not json. Change logFormatType to cri.

```yaml
splunk-kubernetes-logging:
  containers:
    logFormatType: cri
```

**Comment by vinzent** [comment]
Also have a look at the example:

https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/examples/openshift4-logging-only.yaml

**Comment by abudavis** [comment]
Thank you, that was it! Do you also know how to send logs only from 2 namespaces? I tried  to do this (see below) in the values.yaml. Is this the correct way to do it? I additionally annotated the namespace (oc annotate namespace kube-system splunk.com/index=k8s_events)
```
---
objects:
    core:
      v1:
        - name: pods
          namespace: kube-system, openshift-logging
        - name: namespaces
        - name: nodes
        - name: events
          mode: watch
---
objects:
    core:
      v1:
        - name: pods
          namespace: kube-system
        - name: namespaces
        - name: nodes
        - name: events
          mode: watch
---
```
