### ISSUE TITLE
Not able to just send the audit logs without sending all workload container logs

### ISSUE THREAD

**Issue by donflavour** [splunk/splunk-connect-for-kubernetes#610]
**What happened**:
After installing splunk-connect for kubernetes no audit-logs are received in splunk.

**What you expected to happen**:
Audit-logs are successfully sent to splunk. No other container-logs should be sent to splunk

**How to reproduce it (as minimally and precisely as possible)**:
```
global:
  splunk:
    hec:
      token: xxx
      host: xxx
      port: xxx
      insecureSSL: true
      indexName: xxx
  kubernetes:
    clusterName: xxx

splunk-kubernetes-logging:
  enabled: true
  kubernetes:
    # the next actually sets .securityContext.privileged
    # privileged is required, due to SELinux preventing
    # write access for the *.pos files of fluentd.
    securityContext: true
  fluentd:
    exclude_path:
      - /var/log/containers/*.log
  containers:
    logFormatType: cri
    logFormat: "%Y-%m-%dT%H:%M:%S.%N%:z"
  logs:
    # The `kube-audit` file has another path on OpenShift
    kube-audit:
      from:
        file:
          path: /var/log/kube-apiserver/audit.log
    # Next 2 logfiles are specific to OpenShift
    openshift-audit:
      from:
        file:
          path: /var/log/openshift-apiserver/audit.log
      timestampExtraction:
        format: "%Y-%m-%dT%H:%M:%SZ"
      sourcetype: kube:openshift-apiserver-audit
    oauth-audit:
      from:
        file:
          path: /var/log/oauth-apiserver/audit.log
      timestampExtraction:
        format: "%Y-%m-%dT%H:%M:%SZ"
      sourcetype: kube:oauth-apiserver-audit

splunk-kubernetes-metrics:
  enabled: false
splunk-kubernetes-objects:
  enabled: false
```

Installed via helmv3:
` helm install splunk-connect -f values.yaml splunk-connect-for-kubernetes-1.4.7.tgz`

**Anything else we need to know?**:
It's happening on a openshift 4.7 cluster

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: 4.7.7
Server Version: 4.7.7
Kubernetes Version: v1.20.0+c8905da`

- Splunk version: 8.1.4

- Splunk Connect for Kubernetes helm chart version: 1.4.7
