### ISSUE TITLE
Metrics Pod Error in scraping containers from kubelet & 403 Forbidden Errors

### ISSUE THREAD

**Issue by matthewmodestino** [splunk/splunk-connect-for-kubernetes#62]
With the deprecation of Heapster in recent versions of Kubernetes, I have see the Splunk Connect for Kubernetes Metrics pod throw errors about not being able to scrape the Kubelet. Here are two issues I have seen and the workarounds that got me around them:

### splunk-kubernetes-metrics pod shows error scraping kubelet

```
kubectl -n splunk logs -f kubecon-demo-2018-splunk-kubernetes-metrics-6b65bfdc48-4wg99 -c splunk-heapster
```

```
E1220 21:36:05.021124       1 manager.go:101] Error in scraping containers from kubelet:10.0.14.200:10255: failed to get all container stats from Kubelet URL "http://10.0.14.200:10255/stats/container/": Post http://10.0.14.200:10255/stats/container/: dial tcp 10.0.14.200:10255: getsockopt: connection refused
```

Workaround:

Having seen this in the past with Openshift deployments, I edit the metrics deployment and update the heapster commands to point to the secure kubelet port 10250. 

```
kubectl -n splunk edit deployment kubecon-demo-2018-splunk-kubernetes-metrics
```

```
spec:
      serviceAccountName: splunk-kubernetes-metrics
      containers:
      - image: k8s.gcr.io/heapster-amd64:v1.5.1
        imagePullPolicy: IfNotPresent
        name: splunk-heapster
        command:
        - "/heapster"
        #--source=kubernetes"
        - "--source=kubernetes:https://kubernetes.default.svc?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250&insecure=true"
        - "--sink=statsd:udp://127.0.0.1:9001"
```

Once the update to the deployment rolls the pods, you will see that the connection refused error has turned to a 403 forbidden error. 

### After updating heapster command splunk-kubernetes-metrics pod shows 403 forbidden errors

```
kubectl -n splunk logs -f kubecon-demo-2018-splunk-kubernetes-metrics-697d7f6578-gjvp2 -c splunk-heapster
```

```
E1220 21:41:05.139272       1 manager.go:101] Error in scraping containers from kubelet:10.0.16.160:10255: failed to get all container stats from Kubelet URL "http://10.0.16.160:10255/stats/container/": Post http://10.0.16.160:10255/stats/container/: dial tcp 10.0.16.160:10255: getsockopt: connection refused
```

These appear to be caused by the fact we assume the `system:heapster` role to be available. Because it is absent in many deploys now, we will update the binding and give the `splunk-kubernetes-metrics` role `cluster-admin`. 

```
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: splunk-kubernetes-metrics
  namespace: splunk
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: splunk-kubernetes-metrics
    namespace: splunk
```

```
kubectl -n splunk apply -f patch-splunk-kubernetes-metrics-roleBinding.yaml
```

Once applied you should see you are now receiving metrics.
