### ISSUE TITLE
agent drops data with a return between the lines

### ISSUE THREAD

**Issue by tehlers320** [splunk/splunk-connect-for-kubernetes#663]
**What happened**:

```
2021-10-05T23:19:39,883 type=INFO thread=[grpc-default-executor-19] logger=Foo traceId=1231231234 ddTraceId=Foo checkAcls: response=foo {
--
some_object {
object_reference {
namespace: "foo"
}
relation: "foo"
}
}
user_id: "*-*-*-*"
 
2021-10-05T23:19:39,883 *I AM DROPPED*
```

Forwarder drops log data with spaces in the line. 

**What you expected to happen**:
No dropped logs

**How to reproduce it (as minimally and precisely as possible)**:

```
          splunk-kubernetes-logging:
            enabled: true
            fullnameOverride: splunk-kubernetes-logging
            logLevel: "info"
            fluentd:
              path: /var/log/containers/*.log
              exclude_path:
                - "/var/log/containers/fluent*"
            containers:
              path: /var/log
              pathDest: /var/lib/docker/containers
              logFormatType: json
              logFormat:
              refreshInterval:
```

**Anything else we need to know?**:

**Environment**:
```
dependencies:
  - name: splunk-connect-for-kubernetes
    version: "1.4.6"
    splunkHECVersion: "1.2.4"
    kubeObjectVersion: "1.1.4"
```
