### ISSUE TITLE
How to use a splunk URL instead of protocol/host/port

### ISSUE THREAD

**Issue by dzlab** [splunk/splunk-connect-for-kubernetes#665]
I've a splunk instance behind an application gateway that is exposed with a url like this https://mydomain.com/splunkhec/ 
How can I use this url instead of the protocol/host/port fields in the splunk-connect values configuration file?
```yaml
global:
  logLevel: info
  splunk:
    hec:
      # host is required and should be provided by user
      host:
      # port to HEC, optional, default 8088
      port:
      # token is required and should be provided by user
      token:
      # protocol has two options: "http" and "https", default is "https"
      # For self signed certficate leave this field blank
      protocol:
```
