### ISSUE TITLE
Pods erroring with Failed POST to splunk instance url

### ISSUE THREAD

**Issue by cmdub** [splunk/splunk-connect-for-kubernetes#693]
**What happened**:

Getting failed to post error messages in logging/metrics pods:

`2021-12-23 15:45:44 +0000 [error]: #0 Fluent::Plugin::SplunkHecOutput: Failed POST to https://mysplunkcloudinstance.splunkcloud.com/services/collector, response: <!doctype html><html><head><meta http-equiv="content-type" content="text/html; charset=UTF-8"><meta http-equiv="refresh" content="1;url=https://mysplunkcloudinstance.splunkcloud.com/en-US/services/collector"><title>303 See Other</title></head><body><h1>See Other</h1><p>The resource has moved temporarily <a href="https://mysplunkcloudinstance.splunkcloud.com/en-US/services/collector">here</a>.</p></body></html>
2021-12-23 15:45:49 +0000 [error]: #0 Failed POST to https://mysplunkcloudinstance.splunkcloud.com/services/collector, response: <!doctype html><html><head><meta http-equiv="content-type" content="text/html; charset=UTF-8"><meta http-equiv="refresh" content="1;url=https://mysplunkcloudinstance.splunkcloud.com/en-US/services/collector"><title>303 See Other</title></head><body><h1>See Other</h1><p>The resource has moved temporarily <a href="https://mysplunkcloudinstance.splunkcloud.com/en-US/services/collector">here</a>.</p></body></html>`

**What you expected to happen**:

Logs get sent successfully :)

**How to reproduce it (as minimally and precisely as possible)**:
Use these chart values;

```
global:
  kubernetes:
    clusterName: myCluster
  logLevel: info
  metrics:
    service:
      enabled: true
      headless: true
  monitoring_agent_enabled: true
  monitoring_agent_index_name: myApp_dev-monitoring
  prometheus_enabled: true
  serviceMonitor:
    additionalLabels: {}
    enabled: false
    interval: ""
    metricsPort: 24231
    scrapeTimeout: 10s
  splunk:
    hec:
      host: mysplunkcloudinstance.splunkcloud.com
      indexRouting: false
      insecureSSL: false
      port: 443
      protocol: https
      token: myToken
splunk-kubernetes-logging:
  affinity: {}
  buffer:
    '@type': memory
    chunk_limit_records: 100000
    chunk_limit_size: 20m
    flush_interval: 5s
    flush_thread_count: 1
    overflow_action: block
    retry_max_times: 5
    retry_type: periodic
    total_limit_size: 600m
  charEncodingUtf8: false
  containers:
    logFormat: null
    logFormatType: json
    path: /var/log
    pathDest: /var/lib/docker/containers
    refreshInterval: null
    removeBlankEvents: true
  customFilters: {}
  customMetadata: null
  customMetadataAnnotations: null
  enabled: true
  environmentVar: null
  extraVolumeMounts: []
  extraVolumes: []
  fluentd:
    exclude_path: null
    path: /var/log/containers/*.log
  image:
    name: splunk/fluentd-hec
    pullPolicy: IfNotPresent
    pullSecretName: null
    registry: docker.io
    tag: 1.2.9
    usePullSecret: false
  indexFields: []
  journalLogPath: /run/log/journal
  k8sMetadata:
    cache_ttl: 3600
    podLabels:
    - app
    - k8s-app
    - release
    - environment
    - region
    watch: true
  kubernetes:
    clusterName: myCluster
    securityContext: false
  logLevel: info
  logs:
    dns-controller:
      from:
        pod: dns-controller
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:dns-controller
      timestampExtraction:
        format: '%m%d %H:%M:%S.%N'
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
    dns-sidecar:
      from:
        container: sidecar
        pod: kube-dns
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:kubedns-sidecar
      timestampExtraction:
        format: '%m%d %H:%M:%S.%N'
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
    dnsmasq:
      from:
        pod: kube-dns
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:dnsmasq
      timestampExtraction:
        format: '%m%d %H:%M:%S.%N'
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
    docker:
      from:
        journald:
          unit: docker.service
      sourcetype: kube:docker
      timestampExtraction:
        format: '%Y-%m-%dT%H:%M:%S.%NZ'
        regexp: time="(?<time>\d{4}-\d{2}-\d{2}T[0-2]\d:[0-5]\d:[0-5]\d.\d{9}Z)"
    etcd:
      from:
        container: etcd-container
        pod: etcd-server
      timestampExtraction:
        format: '%Y-%m-%d %H:%M:%S.%N'
        regexp: (?<time>\d{4}-\d{2}-\d{2} [0-2]\d:[0-5]\d:[0-5]\d\.\d{6})
    etcd-events:
      from:
        container: etcd-container
        pod: etcd-server-events
      timestampExtraction:
        format: '%Y-%m-%d %H:%M:%S.%N'
        regexp: (?<time>\d{4}-[0-1]\d-[0-3]\d [0-2]\d:[0-5]\d:[0-5]\d\.\d{6})
    etcd-minikube:
      from:
        container: etcd
        pod: etcd-minikube
      timestampExtraction:
        format: '%Y-%m-%d %H:%M:%S.%N'
        regexp: (?<time>\d{4}-\d{2}-\d{2} [0-2]\d:[0-5]\d:[0-5]\d\.\d{6})
    kube-apiserver:
      from:
        pod: kube-apiserver
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:kube-apiserver
      timestampExtraction:
        format: '%m%d %H:%M:%S.%N'
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
    kube-audit:
      from:
        file:
          path: /var/log/kube-apiserver-audit.log
      sourcetype: kube:apiserver-audit
      timestampExtraction:
        format: '%Y-%m-%dT%H:%M:%SZ'
    kube-controller-manager:
      from:
        pod: kube-controller-manager
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:kube-controller-manager
      timestampExtraction:
        format: '%m%d %H:%M:%S.%N'
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
    kube-dns-autoscaler:
      from:
        container: autoscaler
        pod: kube-dns-autoscaler
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:kube-dns-autoscaler
      timestampExtraction:
        format: '%m%d %H:%M:%S.%N'
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
    kube-proxy:
      from:
        pod: kube-proxy
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:kube-proxy
      timestampExtraction:
        format: '%m%d %H:%M:%S.%N'
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
    kube-scheduler:
      from:
        pod: kube-scheduler
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:kube-scheduler
      timestampExtraction:
        format: '%m%d %H:%M:%S.%N'
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
    kubedns:
      from:
        pod: kube-dns
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:kubedns
      timestampExtraction:
        format: '%m%d %H:%M:%S.%N'
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
    kubelet:
      from:
        journald:
          unit: kubelet.service
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:kubelet
      timestampExtraction:
        format: '%m%d %H:%M:%S.%N'
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
  nodeSelector:
    beta.kubernetes.io/os: linux
  podAnnotations: null
  podSecurityPolicy:
    apiGroup: policy
    apparmor_security: true
    create: false
  priorityClassName: null
  rbac:
    create: true
    openshiftPrivilegedSccBinding: false
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
  secret:
    create: true
    name: null
  sendAllMetadata: false
  serviceAccount:
    create: true
    name: null
  sourcetypePrefix: kube
  splunk:
    hec:
      indexName: myApp_dev
    ingest_api:
      debugIngestAPI: null
      eventsEndpoint: null
      ingestAPIHost: null
      ingestAuthHost: null
      serviceClientIdentifier: null
      serviceClientSecretKey: null
      tenant: null
      tokenEndpoint: null
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
splunk-kubernetes-metrics:
  affinity: {}
  aggregatorBuffer:
    '@type': memory
    chunk_limit_records: 10000
    chunk_limit_size: 10m
    flush_interval: 5s
    flush_thread_count: 1
    overflow_action: block
    retry_max_times: 5
    retry_type: periodic
    total_limit_size: 400m
  aggregatorTolerations: {}
  buffer:
    '@type': memory
    chunk_limit_records: 10000
    chunk_limit_size: 10m
    flush_interval: 5s
    flush_thread_count: 1
    overflow_action: block
    retry_max_times: 5
    retry_type: periodic
    total_limit_size: 400m
  customFilters: {}
  customFiltersAggr: {}
  enabled: true
  environmentVar: null
  environmentVarAgg: null
  image:
    name: splunk/k8s-metrics
    pullPolicy: IfNotPresent
    pullsecretName: null
    registry: docker.io
    tag: 1.1.8
    usePullSecret: false
  imageAgg:
    name: splunk/k8s-metrics-aggr
    pullPolicy: IfNotPresent
    pullsecretName: null
    registry: docker.io
    tag: 1.1.8
    usePullSecret: false
  kubernetes:
    bearerTokenFile: null
    caFile: null
    clusterName: null
    insecureSSL: false
    kubeletAddress: null
    kubeletPort: null
    kubeletPortAggregator: null
    secretDir: null
    useRestClientSSL: true
  logLevel: info
  metricsInterval: 15s
  nodeSelector:
    beta.kubernetes.io/os: linux
  podAnnotations: null
  podAnnotationsAgg: null
  podSecurityPolicy:
    apiGroup: policy
    apparmor_security: true
    create: false
  priorityClassName: null
  priorityClassNameAgg: null
  rbac:
    create: true
  resources:
    fluent:
      limits:
        cpu: 200m
        memory: 300Mi
      requests:
        cpu: 200m
        memory: 300Mi
  secret:
    create: true
    name: null
  serviceAccount:
    create: true
    name: null
    usePullSecrets: false
  splunk:
    hec:
      indexName: myApp_dev-monitoring
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
splunk-kubernetes-objects:
  affinity: {}
  buffer:
    '@type': memory
    chunk_limit_records: 10000
    chunk_limit_size: 20m
    flush_interval: 5s
    flush_thread_count: 1
    overflow_action: block
    retry_max_times: 5
    retry_type: periodic
    total_limit_size: 600m
  checkpointFile:
    name: kubernetes-objects.pos
    volume: null
  customFilters: {}
  enabled: false
  environmentVar: null
  image:
    name: splunk/kube-objects
    pullPolicy: IfNotPresent
    pullSecretName: null
    registry: docker.io
    tag: 1.1.9
    usePullSecret: false
  indexFields: []
  kubernetes:
    bearerTokenFile: null
    caFile: null
    clientCert: null
    clientKey: null
    clusterName: null
    insecureSSL: false
    secretDir: null
    url: null
  logLevel: null
  nodeSelector:
    beta.kubernetes.io/os: linux
  objects:
    core:
      v1:
      - name: pods
      - name: namespaces
      - name: nodes
      - mode: watch
        name: events
  podAnnotations: null
  podSecurityPolicy:
    apiGroup: policy
    apparmor_security: true
    create: false
  priorityClassName: null
  rbac:
    create: true
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
  secret:
    create: true
    name: null
  serviceAccount:
    create: true
    name: null
    usePullSecrets: false
  splunk:
    hec:
      caFile: null
      caPath: null
      clientCert: null
      clientKey: null
      host: null
      indexName: null
      indexRouting: false
      insecureSSL: null
      protocol: null
      token: null
  tolerations: []
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21 / EKS
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version: 8.2.2111
- Splunk Connect for Kubernetes helm chart version: 1.4.11
- Others:
