### ISSUE TITLE
Adjust SecurityContext

### ISSUE THREAD

**Issue by MarcoSchaar** [splunk/splunk-connect-for-kubernetes#698]
dear supporting community,

**What would you like to be added**:

would it be possible to introduce the option to different user context like
```yaml
securityContext:
          runAsUser: {{ .Values.kubernetes.runAsUser }}
          privileged: {{ .Values.kubernetes.securityContext }}
```

**Why is this needed**:
be able to avoid running processes as user 0.

some files with *pos* do have write permission only for root 
Any chance to adjust this to given user ID?
