### ISSUE TITLE
JSON treated as s string

### ISSUE THREAD

**Issue by sl4dy** [splunk/splunk-connect-for-kubernetes#701]
**What happened**:
We run Splunk connect on EKS with pretty default settings and all our apps are logging in JSON format; this is the sample output of kubectl logs
```
{"ts":"2022-01-14 12:39:19.097","level":"INFO","logger":"com.gooddata.tiger.metadata.service.DataSourceService","thread":"DefaultDispatcher-worker-1","traceId":"e290ce0edc5a2081","spanId":"c4041baeca64005d","userId":"admin","orgId":"staging","msg":"getDataSourceNames mappedDataSources=[pg_staging-demo]"}
```
However, the log is treated as a string in Splunk
![image](https://user-images.githubusercontent.com/9281201/149517357-1b3c7517-9601-4226-922a-8677f7a85e33.png)
All double quotes are escaped in the raw content:
```
{"log":"{\"ts\":\"2022-01-14 12:39:19.097\",\"level\":\"INFO\",\"logger\":\"com.gooddata.tiger.metadata.service.DataSourceService\",\"thread\":\"DefaultDispatcher-worker-1\",\"traceId\":\"e290ce0edc5a2081\",\"spanId\":\"c4041baeca64005d\",\"userId\":\"admin\",\"orgId\":\"staging\",\"msg\":\"getDataSourceNames mappedDataSources=[pg_staging-demo]\"}\n","stream":"stdout","docker":{"container_id":"2fe4dc184c4ab3231b03baa91a699ceb3ce0f5e23ea5f1c9da99039263e23a0a"}.....
```

**What you expected to happen**:
The JSON is treated as JSON, not as a string.

**How to reproduce it (as minimally and precisely as possible)**:
Behaves like this by default.

**Anything else we need to know?**:
-

**Environment**:
- Kubernetes version (use `kubectl version`): many of 1.20 and 1.21
- Ruby version (use `ruby --version`): -
- OS (e.g: `cat /etc/os-release`): -
- Splunk version: 8.1.7.2
- Splunk Connect for Kubernetes helm chart version: 1.4.10
- Others:

**Comment by ankit-splunk** [comment]
Hey @sl4dy,
based on the given log `{"log":"{\"ts\":\"2022-01-14 12:39:19.097\",\"level\":\"INFO\",\"logger\":\"com.gooddata.tiger.metadata.service.DataSourceService\",\"thread\":\"DefaultDispatcher-worker-1\",\"traceId\":\"e290ce0edc5a2081\",\"spanId\":\"c4041baeca64005d\",\"userId\":\"admin\",\"orgId\":\"staging\",\"msg\":\"getDataSourceNames mappedDataSources=[pg_staging-demo]\"}\n","stream":"stdout","docker":{"container_id":"2fe4dc184c4ab3231b03baa91a699ceb3ce0f5e23ea5f1c9da99039263e23a0a"}`.
 Due to this escape character, this problem occurs. I tried with normal logs v/s escape character contains log, and gets below result. based on the result on Splunk, you can see a difference between both events ingested on Splunk.
![image](https://user-images.githubusercontent.com/89519839/150124240-eef30615-4039-467d-abf4-8ace6980e3d9.png)

**Comment by matthewmodestino** [comment]
This is not the format connect for k8s sends.

What have you deployed? 

SCK specifically parses the container logs as json and strips the unecessary wrapper off the event, allowing just the log record to come in the way it should.

Please advise how/what you have deployed.

**Comment by sl4dy** [comment]
These are my values:
```
global:
  splunk:
    hec:
      host: splunk-ds.na.xxx.com
      port: 8088
      protocol: https
      insecureSSL: true
      indexName: dev-cn
  kubernetes:
    clusterName: "tiger-dev"
  prometheus_enabled: true
  monitoring_agent_enabled: true
  serviceMonitor:
    enabled: false
splunk-kubernetes-logging:
  enabled: true
  logs:
    docker:
      from:
        journald:
          unit: docker.service
      timestampExtraction:
        regexp: time="(?<time>\d{4}-\d{2}-\d{2}T[0-2]\d:[0-5]\d:[0-5]\d.\d{9}Z)"
        format: "%Y-%m-%dT%H:%M:%S.%NZ"
      sourcetype: pnt-k8s
    kubelet:
      from:
        journald:
          unit: kubelet.service
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: pnt-k8s
    kube-apiserver:
      from:
        pod: kube-apiserver
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: pnt-k8s
    kube-scheduler:
      from:
        pod: kube-scheduler
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: pnt-k8s
    kube-controller-manager:
      from:
        pod: kube-controller-manager
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: pnt-k8s
    kube-proxy:
      from:
        pod: kube-proxy
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: pnt-k8s
    ingress-nginx-controller:
      from:
        pod: ingress-nginx-controller
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: pnt-k8s
    aws-node:
      from:
        pod: aws-node
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: pnt-k8s
    coredns:
      from:
        pod: coredns
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: pnt-k8s
    metrics-server:
      from:
        pod: metrics-server
      sourcetype: pnt-k8s
    external-dns:
      from:
        pod: external-dns
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: pnt-k8s
    ebs-csi-controller:
      from:
        pod: ebs-csi-controller
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: pnt-k8s
    kube-audit:
      from:
        file:
          path: /var/log/kube-apiserver-audit.log
      timestampExtraction:
        format: "%Y-%m-%dT%H:%M:%SZ"
      sourcetype: pnt-k8s
    pulsar-release-zookeeper:
      from:
        pod: pulsar-release-zookeeper
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: pulsar
    pulsar-release-recovery:
      from:
        pod: pulsar-release-recovery
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: pulsar
    pulsar-release-broker:
      from:
        pod: pulsar-release-broker
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: pulsar
    pulsar-release-bookie-init:
      from:
        pod: pulsar-release-bookie-init
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: pulsar
    pulsar-release-pulsar-init:
      from:
        pod: pulsar-release-pulsar-init
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: pulsar
    acme-home-ui:
      from:
        pod: acme-home-ui
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: k8s
    acme-ldm-modeler:
      from:
        pod: acme-ldm-modeler
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: k8s
    acme-measure-editor:
      from:
        pod: acme-measure-editor
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: k8s
    acme-cn-metadata-api:
      from:
        pod: acme-cn-metadata-api
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: k8s
    acme-organization-controller:
      from:
        pod: acme-organization-controller
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: k8s
    acme-result-cache:
      from:
        pod: acme-result-cache
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: k8s
    acme-scan-model:
      from:
        pod: acme-scan-model
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: k8s
    acme-sql-executor:
      from:
        pod: acme-sql-executor
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: k8s
    acme-tools:
      from:
        pod: acme-tools
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: k8s
    acme-dex:
      from:
        pod: acme-dex
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: k8s
    acme-db-pgpool:
      from:
        pod: acme-db-pgpool
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: k8s
    acme-afm-exec-api:
      from:
        pod: acme-afm-exec-api
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: k8s
    acme-analytical-designer:
      from:
        pod: acme-analytical-designer
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: k8s
    acme-apidocs:
      from:
        pod: acme-apidocs
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: k8s
    acme-aqe:
      from:
        pod: acme-aqe
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: k8s
    acme-auth-service:
      from:
        pod: acme-auth-service
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: k8s
    acme-dashboards:
      from:
        pod: acme-dashboards
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: k8s
    acme-db-postgresql:
      from:
        pod: acme-db-postgresql
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: k8s
    acme-redis-ha-server:
      from:
        pod: acme-redis-ha-server
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: k8s
  resources:
    limits:
      cpu: 200m
      memory: 600Mi
    requests:
      cpu: 100m
      memory: 200Mi
  sendAllMetadata: true
splunk-kubernetes-objects:
  enabled: false
splunk-kubernetes-metrics:
  enabled: false
```
