### ISSUE TITLE
Defined sourcetype is ignored

### ISSUE THREAD

**Issue by Rohlik** [splunk/splunk-connect-for-kubernetes#709]
**What happened**:
Setting `sourcetype` is totally ignored.
Having something like this (bellow) should set sourcetype to `pnt-k8s` but in Splunk are logs with `sourcetype` set to: `kube:container:external-dns`.
```
        external-dns:
          from:
            pod: external-dns
          multiline:
            firstline: /^\w[0-1]\d[0-3]\d/
          sourcetype: pnt-k8s
```
Docs:https://github.com/splunk/splunk-connect-for-kubernetes/blob/59a8dbcca70528b60b2ba84df5decf2fd3ebd25c/helm-chart/splunk-connect-for-kubernetes/values.yaml#L279-L281
**What you expected to happen**:
I would expect that defined `sourcetype` overwrite default form _PREFIX:container:CONTAINER_NAME_

**How to reproduce it (as minimally and precisely as possible)**:
Define log source from pod and set `sourcetype` to anything you like.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21
- Ruby version (use `ruby --version`): 2.7.4p191
- OS (e.g: `cat /etc/os-release`): AWS EKS RHEL 8.5
- Splunk version: 8.1.7.2
- Splunk Connect for Kubernetes helm chart version: 1.4.11
