### ISSUE TITLE
1.4.12 broke our custom filters that redirect to a different index based on log text

### ISSUE THREAD

**Issue by pc-mreeves** [splunk/splunk-connect-for-kubernetes#724]
**What happened**:
We have this setting:
```
customFilters:
  securityLogFilter:
    tag: tail.containers.var.log.containers.*-app*-service*.log # all service containers
    type: jq_transformer
    body: jq 'if (.record.log | contains("FOOBAR_SECURITY")) then (.record.splunk_index="foobar_security" | .record) else .record end'
```

**What you expected to happen**:
In 1.4.11 that means any log entry with "FOOBAR_SECURITY" in it, gets routed to the foobar_security index.

In 1.4.12 it gets routed the default index that all the rest of the splunk logs get sent to.

I suspect this is due to this change: https://github.com/splunk/splunk-connect-for-kubernetes/pull/696 where it now uses a CUSTOM label instead of the CONCAT label. 

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
   $ kunectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:51:12Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version:
- Splunk Connect for Kubernetes helm chart version:
  1.4.12
- Others:
