### ISSUE TITLE
Configure HTTP(S) proxy to connect to HEC on splunk Cloud instance

### ISSUE THREAD

**Issue by npeyrussie** [splunk/splunk-connect-for-kubernetes#753]
Hi,

Is there a way to connect Splunk Connect for Kubernetes to HEC on Splunk Cloud instance through a HTTP(S) Proxy ?

Is it possible to use `environmentVar:` in values.yml file ?

If yes, what are the variables and the format to use ?

 
Regards.

Nicolas.

**Comment by npeyrussie** [comment]
Hello, 

Sorry, I found by myself

```
splunk-kubernetes-logging:
  environmentVar:
    - name: HTTP_PROXY
      value: http://my_proxy:myport
    - name: HTTPS_PROXY
      value: http://my_proxy:myport
```

Regards
