### ISSUE TITLE
Logs are not visible in splunk pods

### ISSUE THREAD

**Issue by kavita1205** [splunk/splunk-connect-for-kubernetes#762]
**What happened**:
I have followed all the steps mentioned in the github page to install splunk in k8 cluster:
helm repo add splunk https://splunk.github.io/splunk-connect-for-kubernetes/
helm inspect values splunk/splunk-connect-for-kubernetes > values.yaml
helm install my-splunk-connect -f values.yaml splunk/splunk-connect-for-kubernetes
 
Also as per client need , I have used below mentioned values.yaml file to install. Now I am seeing all splunk pods are running in cluster but when I see logs of these pods then it show me "back-slashes" i.e. "\\\\\\\\". 

Can someone help me in fixing this issue.
```
 global:
  logLevel: info
  splunk:
    hec:
      host: splunk-hec.oi.tivo.com
      insecureSSL: true
      port: 8088
      protocol: https
      token: 779EE032-1473-40F8-AA19-DBEFFE60E51B
splunk-kubernetes-logging:
  journalLogPath: /var/log/journal
  kubernetes:
    clusterName: ****-ml-lv-2
  splunk:
    hec:
      indexName: ml_logs
      indexRouting: false
      indexRoutingDefaultIndex: default
splunk-kubernetes-metrics:
  kubernetes:
    clusterName: ****-ml-lv-2
    insecureSSL: true
    kubeletAddress: '"#{ENV[''KUBERNETES_NODE_IP'']}"'
    kubeletPort: 10250
    useRestClientSSL: true
  metricsInterval: 60s
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-metrics
  splunk:
    hec:
      indexName: em_metrics
splunk-kubernetes-objects:
  kubernetes:
    clusterName: *****-ml-lv-2
    insecureSSL: true
  objects:
    apps:
      v1:
      - interval: 60s
        name: daemon_sets
    core:
      v1:
      - interval: 60s
        name: pods
      - interval: 60s
        name: nodes
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-objects
  splunk:
    hec:
      indexName: em_meta
```

**What you expected to happen**:
logs should be clearly visible in splunk pods and these logs should be sent to splunk web page too.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version:
- Splunk Connect for Kubernetes helm chart version:
- Others:
