### ISSUE TITLE
Pod logs are not pushed to splunk

### ISSUE THREAD

**Issue by kavita1205** [splunk/splunk-connect-for-kubernetes#763]
**What happened**:
Pod logs are not being pushed to splunk. I am using below value.yaml file. When I am trying to search in splunk then I am getting this error message. Please see screenshot:

splunk error message:

```
DAG Execution Exception: Search has been cancelled
Search auto-canceled
[ssidx04.oip1.tivo.com] Timed out waiting for peer ssidx04.oip1.tivo.com:ingest_pipe=1. Search results might be incomplete! If this occurs frequently, receiveTimeout in distsearch.conf might need to be increased.
[ssidx08.oip1.tivo.com] Timed out waiting for peer ssidx08.oip1.tivo.com:ingest_pipe=1. Search results might be incomplete! If this occurs frequently, receiveTimeout in distsearch.conf might need to be increased.
The search job has failed due to an error. You may be able view the job in the [Job Inspector](https://splunk-engr.oi.tivo.com/en-US/app/search/search?q=search%20cluster_name%3A%20xperi-ml-lv-2&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=&earliest=rt-30m&latest=rt&sid=rt_1651723924.280714_51E8DCDB-8A04-44B9-A5FC-F86DBED92279#).

```

**Values.yaml file**

```
global:
  logLevel: info
  splunk:
    hec:
      host: splunk-hec.oi.tivo.com
      insecureSSL: true
      port: 8088
      protocol: https
      token: FECACF54-6904-46C4-9E92-E5A1E8A89AE1
splunk-kubernetes-logging:
  journalLogPath: /var/log/journal
  containers:
    # Path to root directory of container logs
    path: /var/log
    # Final volume destination of container log symlinks
    pathDest: /var/lib/docker/containers
    # Log format type, "json" or "cri"
    logFormatType: cri
    # Specify the logFormat for "cri" logFormatType - provide time format
    # For example "%Y-%m-%dT%H:%M:%S.%N%:z" for openshift, "%Y-%m-%dT%H:%M:%S.%NZ" for IBM IKS
    # Default for "cri": "%Y-%m-%dT%H:%M:%S.%N%:z"
    # For "json", the log format cannot be changed: "%Y-%m-%dT%H:%M:%S.%NZ"
    logFormat:
    # Specify the interval of refreshing the list of watch file.
    refreshInterval:
    # Boolean to whether to remove blank events or not
    removeBlankEvents: true
    # Boolean if true, uses local time. UTC. Otherwise, UTC is used
    localTime: false
  buffer:
    "@type": memory
    total_limit_size: 600m
    chunk_limit_size: 20m
    chunk_limit_records: 100000
    flush_interval: 5s
    flush_thread_count: 1
    overflow_action: block
    retry_max_times: 5
    retry_type: periodic
  kubernetes:
    clusterName: xperi-ml-lv-2
  splunk:
    hec:
      indexName: ml_logs
      indexRouting: false
      indexRoutingDefaultIndex: default
splunk-kubernetes-metrics:
  kubernetes:
    clusterName: xperi-ml-lv-2
    insecureSSL: true
    kubeletAddress: '"#{ENV[''KUBERNETES_NODE_IP'']}"'
    kubeletPort: 10250
    useRestClientSSL: true
  metricsInterval: 60s
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-metrics
  splunk:
    hec:
      indexName: em_metrics
```
# Controls the resources used by the fluentd daemonset
  resources:
    fluent:
      limits:
        cpu: 200m
        memory: 300Mi
      requests:
        cpu: 200m
        memory: 300Mi
  # Controls the output buffer for fluentd for the metrics pod
  # Note that, for memory buffer, if `resources.sidecar.limits.memory` is set,
  # the total buffer size should not bigger than the memory limit, it should also
  # consider the basic memory usage by fluentd itself.
  # All buffer parameters (except Argument) defined in
  # https://docs.fluentd.org/v1.0/articles/buffer-section#parameters
  # can be configured here.
  buffer:
    "@type": memory
    total_limit_size: 400m
    chunk_limit_size: 10m
    chunk_limit_records: 10000
    flush_interval: 5s
    flush_thread_count: 1
    overflow_action: block
    retry_max_times: 10
    retry_type: periodic
    retry_wait: 30

  # Controls the output buffer for fluentd for the metrics aggregator pod
  aggregatorBuffer:
    "@type": memory
    total_limit_size: 400m
    chunk_limit_size: 10m
    chunk_limit_records: 10000
    flush_interval: 5s
    flush_thread_count: 1
    overflow_action: block
    retry_max_times: 10
    retry_type: periodic
    retry_wait: 30

splunk-kubernetes-objects:
  kubernetes:
    clusterName: xperi-ml-lv-2
    insecureSSL: true
  objects:
    apps:
      v1:
      - interval: 60s
        name: daemon_sets
    core:
      v1:
      - interval: 60s
        name: pods
      - interval: 60s
        name: nodes
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-objects
  splunk:
    hec:
      indexName: em_meta
**What you expected to happen**:
Pods log should be pushed to splunk

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.21.9
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version:8.11
- Splunk Connect for Kubernetes helm chart version:1.4.15
- Others:
