### ISSUE TITLE
http_proxy support

### ISSUE THREAD

**Issue by hzproe** [splunk/splunk-connect-for-kubernetes#769]
<

**What would you like to be added**:
Please add support for http_proxy / https_proxy so we can ship logs from our systems to splunkcloud using this plugin

**Why is this needed**:
In our corporate network we cannot connect to Internet without using http_proxy

**Comment by harshit-splunk** [comment]
Hi @hzproe, you can configure proxy by adding them to SCK's env variable.
For example,
```
splunk-kubernetes-logging:
  environmentVar:
    - name: HTTP_PROXY
      value: http://my_proxy:myport
    - name: HTTPS_PROXY
      value: http://my_proxy:myport
```
