### ISSUE TITLE
Error on port 443

### ISSUE THREAD

**Issue by darismendyesp** [splunk/splunk-connect-for-kubernetes#778]
**What happened**:As SC4k8S was configured following the documentation provided it is showing this message error 

Failed to flush the buffer. retry_times=0 next_retry_time=2022-06-08 18:33:16 +0000 chunk="5e0f3ee14338933cc5520f7cef8a03c2" error_class=SocketError error="Failed to open TCP connection to https:443 (getaddrinfo: Name or service not known)"

**What you expected to happen**:Data flowing succesfuly

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version: 8.2.x
- Splunk Connect for Kubernetes helm chart version:
- Others:

**Comment by skirven4** [comment]
What are you sending in your values file? Specifically in the "splunk" stanza. From the looks of it, you need a hec.host? And is your HEC server set to listen on 443? The default is 8088.

```
splunk:
  hec:
    host: <FQDN of HEC Server>
    port: 8088 ## Or other HEC port
    protocol: https
    token: <HEC Token>
    indexName: main # Default index
    insecureSSL: yes
    clientCert:
    clientKey:
    caFile:
  ingest_api:
    serviceClientIdentifier:
    serviceClientSecretKey:
    tokenEndpoint:
    ingestAuthHost:
    ingestAPIHost:
    tenant:
    eventsEndpoint:
    debugIngestAPI:
```
