### ISSUE TITLE
Can not find kubelet logs in splunk

### ISSUE THREAD

**Issue by BrandonTsai** [splunk/splunk-connect-for-kubernetes#779]
**What happened**:

I try to search kubelet logs from splunk. But no logs shows in the result.

**What you expected to happen**:

Get the system logs of each OpenShift node from Splunk 

**How to reproduce it (as minimally and precisely as possible)**:

Do following search: 
index="*" sourcetype="*kubelet*"

**Anything else we need to know?**:

**Environment**:
- OpenShift version:
$ oc version
Client Version: 4.8.14
Server Version: 4.8.39
Kubernetes Version: v1.21.8+ed4d8fd

- Splunk version:
Splunk Enterprise
Version:
8.1.2

- Splunk Connect for Kubernetes helm chart version:
1.4.9

**Comment by BrandonTsai** [comment]
Hi @harshit-splunk ,

in the values.yaml, I saw the kubelet service is specified.
```
    kubelet: &glog
      from:
        journald:
          unit: kubelet.service
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:kubelet
```

But I can not find the journald logs of kubelet.service.
Do these  journald logs forward to splunk or not?

Cheers,

Brandon
