### ISSUE TITLE
[Q] It is possible to use persistent storage with splunk-kubernetes-logging?

### ISSUE THREAD

**Issue by Rohlik** [splunk/splunk-connect-for-kubernetes#806]
Hey there dear community 👋🏽,

We use [splunk-kubernetes-logging](https://github.com/splunk/splunk-connect-for-kubernetes/tree/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging) for collecting logs from our K8S infrastructure and send them to Splunk via Splunk HTTP Event Collector (HEC).  
Sometimes, and you probably know this from your own experiences, underlying infrastructure can be in weird/degraded state.  

For example, your remote Splunk with HEC isn't accessible from that K8S cluster and at the same time you decide to restart your `splunk connect for kubernetes` deployment for some reason.  
At this point, you lost all of your logs which may be in your Fluentd [buffers](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml#L370).  
I would like to remedy this situation by adding persistent storage to each of _splunk-kubernetes-logging_ which will persist across pod's restarts.
Is this supported? Can be this done?

Thank you.

**Comment by harshit-splunk** [comment]
You can use the following config in buffer config:
```
buffer:
    "@type": file
    path: /var/log/containers/ 
    total_limit_size: 2 GB
    overflow_action: block
    retry_forever: true
```

Please tune these configs according to your need. Refer this doc: https://docs.fluentd.org/configuration/buffer-section

**Comment by harshit-splunk** [comment]
@Rohlik, there is one correction. Don't use `/var/log/` for the buffer path. Kubernetes will rotate the buffer file so you will lose the data.

**Comment by Rohlik** [comment]
Thank you @harshit-splunk.
For all who may have same issue, I am putting here related setting:

```yaml
    splunk-kubernetes-logging:
      buffer:
        "@type": file
        total_limit_size: 1GB
        path: /var/lib/fluentd
        overflow_action: block
        retry_forever: true
      extraVolumes:
        - name: fluentd-buffer
          hostPath:
            path: /tmp/fluentd
            type: DirectoryOrCreate
      extraVolumeMounts:
        - name: fluentd-buffer
          mountPath: /var/lib/fluentd
```

**Comment by vinzent** [comment]
```
      extraVolumes:
        - name: fluentd-buffer
          hostPath:
            path: /tmp/fluentd
            type: DirectoryOrCreate
```

`/tmp` might be cleaned on host-reboot or due to some recurring cleanup tasks. 

Also be aware that if you have high-volume of logs, writing all the logs to the buffer file could impact the node and/or fluentd performance.
