### ISSUE TITLE
Enhancement deploymentMetricsAggregator for Topologyspreadconstraint

### ISSUE THREAD

**Issue by heyosi** [splunk/splunk-connect-for-kubernetes#873]
**What would you like to be added**:
I would like to add Topologyspreadconstraint to deployment of /[splunk-kubernetes-metrics](https://github.com/splunk/splunk-connect-for-kubernetes/tree/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics)/[templates](https://github.com/splunk/splunk-connect-for-kubernetes/tree/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates)
```
topologySpreadConstraints:
- maxSkew: 1
  topologyKey: topology.kubernetes.io/zone
  whenUnsatisfiable: DoNotSchedule
  labelSelector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - {{ template "splunk-kubernetes-metrics.name" . }}
```

**Why is this needed**:
You can use topology spread constraints to control how [Pods](https://kubernetes.io/docs/concepts/workloads/pods/) are spread across your cluster among failure-domains such as regions, zones, nodes, and other user-defined topology domains. This can help to achieve high availability as well as efficient resource utilization.
